# Generated by Django 5.1.15 on 2025-12-18 22:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen de la categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('order', models.IntegerField(default=0, help_text='Número menor = aparece primero', verbose_name='Orden de visualización')),
                ('parent', models.ForeignKey(blank=True, help_text='Para crear subcategorías (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.productcategory', verbose_name='Categoría padre')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(blank=True, max_length=320, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, help_text='Código interno del producto', max_length=100, verbose_name='SKU')),
                ('short_description', models.TextField(blank=True, help_text='Texto breve para listados', max_length=500, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada con HTML permitido', verbose_name='Descripción completa')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta al público', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio anterior (para mostrar descuento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de comparación')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisición (no visible al público)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de costo')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Marca')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('is_active', models.BooleanField(default=True, help_text='Producto visible en la tienda', verbose_name='¿Está activo?')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar en sección destacados', verbose_name='¿Es destacado?')),
                ('requires_shipping', models.BooleanField(default=True, help_text='Desactivar para productos digitales', verbose_name='¿Requiere envío?')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta título')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta descripción')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ecommerce.productcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción de la imagen para SEO', max_length=200, verbose_name='Texto alternativo')),
                ('is_primary', models.BooleanField(default=False, help_text='Solo una imagen debe ser principal', verbose_name='¿Es imagen principal?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product', verbose_name='Producto')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad actual en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alerta cuando el stock baje de este número', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Umbral de stock bajo')),
                ('track_inventory', models.BooleanField(default=True, help_text='Desactivar para productos sin límite de stock', verbose_name='¿Controlar inventario?')),
                ('allow_backorders', models.BooleanField(default=False, help_text='Permitir ventas cuando no hay stock', verbose_name='¿Permitir pre-pedidos?')),
                ('total_sold', models.IntegerField(default=0, help_text='Cantidad vendida desde el inicio', verbose_name='Total vendido')),
                ('last_restock_date', models.DateTimeField(blank=True, null=True, verbose_name='Última reposición')),
                ('last_restock_quantity', models.IntegerField(default=0, verbose_name='Cantidad última reposición')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'indexes': [models.Index(fields=['tenant', 'stock'], name='ecommerce_i_tenant__bbfc4b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='ecommerce_p_tenant__e4e835_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tenant', 'slug'], name='ecommerce_p_tenant__47739c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active', 'category'], name='ecommerce_p_tenant__91c2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'slug'], name='ecommerce_p_tenant__df6141_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_featured'], name='ecommerce_p_tenant__8efded_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['tenant', 'product'], name='ecommerce_p_tenant__7d61d7_idx'),
        ),
    ]
