# Generated by Django 6.0 on 2025-12-27 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_uid_multi_tenant_auth'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas o instrucciones especiales del cliente', verbose_name='Notas')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas del staff (no visibles para el cliente)', verbose_name='Notas internas')),
                ('requires_payment', models.BooleanField(default=False, help_text='Si se debe pagar al agendar', verbose_name='¿Requiere pago?')),
                ('is_paid', models.BooleanField(default=False, verbose_name='¿Está pagado?')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='¿Recordatorio enviado?')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio enviado en')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Servicio')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.staffmember', verbose_name='Miembro del staff')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['tenant', 'start_datetime', 'status'], name='bookings_ap_tenant__e24431_idx'), models.Index(fields=['tenant', 'customer'], name='bookings_ap_tenant__b5ce15_idx'), models.Index(fields=['tenant', 'staff_member', 'start_datetime'], name='bookings_ap_tenant__a299eb_idx'), models.Index(fields=['tenant', 'status'], name='bookings_ap_tenant__a043e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Día de la semana')),
                ('open_time', models.TimeField(help_text='Hora en que abre el negocio (ej: 09:00)', verbose_name='Hora de apertura')),
                ('close_time', models.TimeField(help_text='Hora en que cierra el negocio (ej: 18:00)', verbose_name='Hora de cierre')),
                ('is_open', models.BooleanField(default=True, help_text='Si el negocio abre este día', verbose_name='¿Está abierto?')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Horario de Negocio',
                'verbose_name_plural': 'Horarios de Negocio',
                'ordering': ['day_of_week'],
                'indexes': [models.Index(fields=['tenant', 'is_open'], name='bookings_bu_tenant__22cb68_idx')],
                'unique_together': {('tenant', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('start_datetime', models.DateTimeField(help_text='Fecha y hora de inicio del tiempo libre', verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(help_text='Fecha y hora de fin del tiempo libre', verbose_name='Fin')),
                ('reason', models.CharField(blank=True, help_text='Ej: Vacaciones, Feriado, Capacitación', max_length=200, verbose_name='Motivo')),
                ('is_recurring', models.BooleanField(default=False, help_text='Para festivos anuales (ej: Navidad)', verbose_name='¿Es recurrente?')),
                ('staff_member', models.ForeignKey(blank=True, help_text='Dejar vacío si aplica a todo el negocio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='services.staffmember', verbose_name='Miembro del staff')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tiempo Libre',
                'verbose_name_plural': 'Tiempos Libres',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['tenant', 'start_datetime', 'end_datetime'], name='bookings_ti_tenant__640fa5_idx'), models.Index(fields=['tenant', 'staff_member'], name='bookings_ti_tenant__ea5f7a_idx')],
            },
        ),
    ]
