# Generated by Django 6.0 on 2025-12-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Hora en que cierra el negocio (ej: 18:00). Dejar vacío si está cerrado.', null=True, verbose_name='Hora de cierre'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Hora en que abre el negocio (ej: 09:00). Dejar vacío si está cerrado.', null=True, verbose_name='Hora de apertura'),
        ),
    ]
