# Generated by Django on 2025-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_businesshours_nullable_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Expira en",
                help_text="Fecha de expiración para reservas temporales",
            ),
        ),
    ]
