# core/geography.py
"""
Datos geográficos para los países soportados.
Estructura: País → Estado/Departamento → Ciudades principales
"""

# Estructura: {país: {estado: [ciudades]}}
GEOGRAPHY_DATA = {
    "Colombia": {
        "Amazonas": ["Leticia", "Puerto Nariño"],
        "Antioquia": ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Turbo", "Rionegro", "Caldas", "La Estrella", "Sabaneta", "Copacabana", "Caucasia"],
        "Arauca": ["Arauca", "Tame", "Saravena", "Fortul"],
        "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Baranoa", "Puerto Colombia", "Galapa"],
        "Bogotá D.C.": ["Bogotá"],
        "Bolívar": ["Cartagena", "Magangué", "Turbaco", "Arjona", "El Carmen de Bolívar", "San Juan Nepomuceno"],
        "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Puerto Boyacá", "Villa de Leyva"],
        "Caldas": ["Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio", "Anserma"],
        "Caquetá": ["Florencia", "San Vicente del Caguán", "Puerto Rico", "El Doncello"],
        "Casanare": ["Yopal", "Aguazul", "Villanueva", "Tauramena", "Paz de Ariporo"],
        "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía", "El Tambo", "Piendamó"],
        "Cesar": ["Valledupar", "Aguachica", "Bosconia", "Codazzi", "La Jagua de Ibirico", "Chimichagua"],
        "Chocó": ["Quibdó", "Istmina", "Condoto", "Tadó", "Riosucio"],
        "Córdoba": ["Montería", "Cereté", "Lorica", "Sahagún", "Montelíbano", "Planeta Rica", "Tierralta"],
        "Cundinamarca": ["Soacha", "Facatativá", "Zipaquirá", "Chía", "Fusagasugá", "Girardot", "Madrid", "Mosquera", "Funza", "Cajicá", "Cota", "La Calera", "Sibaté", "Tocancipá", "Sopó", "Tabio", "Tenjo", "Villeta", "Pacho"],
        "Guainía": ["Inírida"],
        "Guaviare": ["San José del Guaviare", "Calamar", "El Retorno"],
        "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre", "Palermo"],
        "La Guajira": ["Riohacha", "Maicao", "Uribia", "Manaure", "San Juan del Cesar", "Fonseca"],
        "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "El Banco", "Plato", "Aracataca"],
        "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "San Martín", "Restrepo"],
        "Nariño": ["Pasto", "Tumaco", "Ipiales", "Túquerres", "La Unión", "Samaniego"],
        "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios", "Tibú"],
        "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez", "Villagarzón"],
        "Quindío": ["Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya", "Circasia"],
        "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Belén de Umbría"],
        "San Andrés y Providencia": ["San Andrés", "Providencia"],
        "Santander": ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil", "Socorro"],
        "Sucre": ["Sincelejo", "Corozal", "San Marcos", "Sampués", "Tolú", "San Onofre"],
        "Tolima": ["Ibagué", "Espinal", "Melgar", "Mariquita", "Honda", "Líbano", "Chaparral"],
        "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Cartago", "Buga", "Yumbo", "Jamundí", "Candelaria", "Florida", "Pradera", "Zarzal"],
        "Vaupés": ["Mitú", "Carurú"],
        "Vichada": ["Puerto Carreño", "La Primavera", "Cumaribo"],
    },
    "México": {
        "Aguascalientes": ["Aguascalientes", "Jesús María", "Calvillo", "San Francisco de los Romo"],
        "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Rosarito", "Tecate"],
        "Baja California Sur": ["La Paz", "Los Cabos", "Comondú", "Loreto", "Mulegé"],
        "Campeche": ["Campeche", "Ciudad del Carmen", "Champotón", "Escárcega", "Calkiní"],
        "Chiapas": ["Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas", "Comitán", "Palenque", "Chiapa de Corzo"],
        "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias", "Cuauhtémoc", "Parral", "Nuevo Casas Grandes"],
        "Ciudad de México": ["Ciudad de México"],
        "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña", "Sabinas"],
        "Colima": ["Colima", "Manzanillo", "Tecomán", "Villa de Álvarez", "Armería"],
        "Durango": ["Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro", "El Salto"],
        "Estado de México": ["Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Nezahualcóyotl", "Cuautitlán Izcalli", "Metepec", "Huixquilucan", "Atizapán", "Texcoco"],
        "Guanajuato": ["León", "Irapuato", "Celaya", "Salamanca", "Guanajuato", "San Miguel de Allende", "Silao"],
        "Guerrero": ["Acapulco", "Chilpancingo", "Iguala", "Taxco", "Zihuatanejo", "Chilapa"],
        "Hidalgo": ["Pachuca", "Tulancingo", "Tula", "Actopan", "Huejutla", "Tizayuca"],
        "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta", "Tlajomulco", "Lagos de Moreno", "Tepatitlán"],
        "Michoacán": ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Apatzingán", "Pátzcuaro", "Zitácuaro"],
        "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Yautepec", "Emiliano Zapata"],
        "Nayarit": ["Tepic", "Bahía de Banderas", "Santiago Ixcuintla", "Compostela", "Tuxpan"],
        "Nuevo León": ["Monterrey", "Guadalupe", "San Nicolás", "Apodaca", "Santa Catarina", "General Escobedo", "San Pedro Garza García"],
        "Oaxaca": ["Oaxaca de Juárez", "Salina Cruz", "Juchitán", "Tuxtepec", "Huatulco", "Puerto Escondido"],
        "Puebla": ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "Cholula", "Huauchinango"],
        "Querétaro": ["Querétaro", "San Juan del Río", "Corregidora", "El Marqués", "Tequisquiapan"],
        "Quintana Roo": ["Cancún", "Chetumal", "Playa del Carmen", "Cozumel", "Tulum", "Isla Mujeres"],
        "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala", "Tamazunchale"],
        "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis", "Guasave", "Guamúchil", "Navolato"],
        "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "San Luis Río Colorado", "Navojoa", "Guaymas"],
        "Tabasco": ["Villahermosa", "Cárdenas", "Comalcalco", "Huimanguillo", "Macuspana", "Paraíso"],
        "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico", "Ciudad Victoria", "Altamira", "Ciudad Madero"],
        "Tlaxcala": ["Tlaxcala", "Apizaco", "Huamantla", "San Pablo del Monte", "Chiautempan"],
        "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Poza Rica", "Orizaba", "Boca del Río", "Minatitlán"],
        "Yucatán": ["Mérida", "Valladolid", "Tizimín", "Progreso", "Umán", "Kanasín"],
        "Zacatecas": ["Zacatecas", "Fresnillo", "Guadalupe", "Jerez", "Río Grande", "Sombrerete"],
    },
    "España": {
        "Andalucía": ["Sevilla", "Málaga", "Córdoba", "Granada", "Almería", "Cádiz", "Huelva", "Jaén", "Marbella", "Jerez de la Frontera"],
        "Aragón": ["Zaragoza", "Huesca", "Teruel", "Calatayud", "Utebo"],
        "Asturias": ["Oviedo", "Gijón", "Avilés", "Mieres", "Langreo"],
        "Cantabria": ["Santander", "Torrelavega", "Castro Urdiales", "Camargo", "Piélagos"],
        "Castilla y León": ["Valladolid", "Burgos", "Salamanca", "León", "Palencia", "Zamora", "Ávila", "Segovia", "Soria"],
        "Castilla-La Mancha": ["Toledo", "Albacete", "Ciudad Real", "Guadalajara", "Cuenca", "Talavera de la Reina"],
        "Cataluña": ["Barcelona", "Hospitalet de Llobregat", "Terrassa", "Badalona", "Sabadell", "Tarragona", "Lleida", "Girona", "Mataró", "Reus"],
        "Ceuta": ["Ceuta"],
        "Comunidad Valenciana": ["Valencia", "Alicante", "Elche", "Castellón de la Plana", "Torrevieja", "Benidorm", "Gandía", "Orihuela"],
        "Extremadura": ["Badajoz", "Cáceres", "Mérida", "Plasencia", "Don Benito", "Almendralejo"],
        "Galicia": ["Vigo", "A Coruña", "Ourense", "Lugo", "Santiago de Compostela", "Pontevedra", "Ferrol"],
        "Islas Baleares": ["Palma de Mallorca", "Ibiza", "Manacor", "Santa Eulària des Riu", "Calvià"],
        "Islas Canarias": ["Las Palmas de Gran Canaria", "Santa Cruz de Tenerife", "La Laguna", "Telde", "Arona", "Arrecife"],
        "La Rioja": ["Logroño", "Calahorra", "Arnedo", "Haro", "Alfaro"],
        "Madrid": ["Madrid", "Móstoles", "Alcalá de Henares", "Fuenlabrada", "Leganés", "Getafe", "Alcorcón", "Torrejón de Ardoz", "Parla", "Alcobendas"],
        "Melilla": ["Melilla"],
        "Navarra": ["Pamplona", "Tudela", "Barañáin", "Burlada", "Estella"],
        "País Vasco": ["Bilbao", "Vitoria-Gasteiz", "San Sebastián", "Barakaldo", "Getxo", "Irun", "Portugalete"],
        "Región de Murcia": ["Murcia", "Cartagena", "Lorca", "Molina de Segura", "Alcantarilla", "Yecla"],
    },
    "Argentina": {
        "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil", "San Nicolás de los Arroyos", "Pergamino", "Olavarría", "Junín", "Necochea"],
        "CABA": ["Ciudad Autónoma de Buenos Aires"],
        "Catamarca": ["San Fernando del Valle de Catamarca", "Valle Viejo", "Fray Mamerto Esquiú", "Andalgalá", "Belén"],
        "Chaco": ["Resistencia", "Presidencia Roque Sáenz Peña", "Villa Ángela", "Charata", "General José de San Martín"],
        "Chubut": ["Rawson", "Comodoro Rivadavia", "Trelew", "Puerto Madryn", "Esquel"],
        "Córdoba": ["Córdoba", "Villa María", "Río Cuarto", "San Francisco", "Villa Carlos Paz", "Alta Gracia"],
        "Corrientes": ["Corrientes", "Goya", "Paso de los Libres", "Curuzú Cuatiá", "Mercedes"],
        "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú", "Concepción del Uruguay", "Colón", "Villaguay"],
        "Formosa": ["Formosa", "Clorinda", "Pirané", "El Colorado", "Ingeniero Juárez"],
        "Jujuy": ["San Salvador de Jujuy", "Palpalá", "San Pedro", "Libertador General San Martín", "Perico"],
        "La Pampa": ["Santa Rosa", "General Pico", "Toay", "General Acha", "Eduardo Castex"],
        "La Rioja": ["La Rioja", "Chilecito", "Aimogasta", "Chamical", "Villa Unión"],
        "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz", "Guaymallén", "Las Heras", "Maipú", "Luján de Cuyo"],
        "Misiones": ["Posadas", "Oberá", "Eldorado", "Puerto Iguazú", "Apóstoles", "Jardín América"],
        "Neuquén": ["Neuquén", "San Martín de los Andes", "Zapala", "Cutral Có", "Centenario", "Plottier"],
        "Río Negro": ["Viedma", "San Carlos de Bariloche", "General Roca", "Cipolletti", "Villa Regina", "Allen"],
        "Salta": ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "General Güemes", "Cafayate", "Metán"],
        "San Juan": ["San Juan", "Rawson", "Chimbas", "Rivadavia", "Santa Lucía", "Pocito"],
        "San Luis": ["San Luis", "Villa Mercedes", "Merlo", "La Punta", "Justo Daract"],
        "Santa Cruz": ["Río Gallegos", "Caleta Olivia", "Puerto Deseado", "Pico Truncado", "El Calafate"],
        "Santa Fe": ["Santa Fe", "Rosario", "Rafaela", "Venado Tuerto", "Reconquista", "Santo Tomé", "Villa Gobernador Gálvez"],
        "Santiago del Estero": ["Santiago del Estero", "La Banda", "Termas de Río Hondo", "Añatuya", "Frías"],
        "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin"],
        "Tucumán": ["San Miguel de Tucumán", "Yerba Buena", "Tafí Viejo", "Concepción", "Banda del Río Salí", "Aguilares"],
    },
    "Chile": {
        "Arica y Parinacota": ["Arica", "Putre"],
        "Tarapacá": ["Iquique", "Alto Hospicio", "Pozo Almonte", "Pica"],
        "Antofagasta": ["Antofagasta", "Calama", "Tocopilla", "Mejillones", "Taltal", "San Pedro de Atacama"],
        "Atacama": ["Copiapó", "Vallenar", "Chañaral", "Diego de Almagro", "Caldera"],
        "Coquimbo": ["La Serena", "Coquimbo", "Ovalle", "Illapel", "Los Vilos", "Vicuña"],
        "Valparaíso": ["Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana", "San Antonio", "Quillota", "Los Andes", "San Felipe"],
        "Metropolitana de Santiago": ["Santiago", "Puente Alto", "Maipú", "La Florida", "Las Condes", "San Bernardo", "Peñalolén", "Providencia", "Ñuñoa", "Vitacura"],
        "O'Higgins": ["Rancagua", "San Fernando", "Rengo", "Machali", "Santa Cruz", "Graneros"],
        "Maule": ["Talca", "Curicó", "Linares", "Constitución", "Cauquenes", "Molina"],
        "Ñuble": ["Chillán", "San Carlos", "Chillán Viejo", "Coihueco", "Bulnes"],
        "Biobío": ["Concepción", "Talcahuano", "Los Ángeles", "Chiguayante", "Coronel", "San Pedro de la Paz", "Hualpén"],
        "La Araucanía": ["Temuco", "Padre Las Casas", "Villarrica", "Angol", "Pucón", "Victoria"],
        "Los Ríos": ["Valdivia", "La Unión", "Río Bueno", "Panguipulli", "Los Lagos"],
        "Los Lagos": ["Puerto Montt", "Osorno", "Puerto Varas", "Castro", "Ancud", "Calbuco"],
        "Aysén": ["Coyhaique", "Puerto Aysén", "Chile Chico", "Cochrane"],
        "Magallanes": ["Punta Arenas", "Puerto Natales", "Porvenir", "Puerto Williams"],
    },
    "Perú": {
        "Amazonas": ["Chachapoyas", "Bagua", "Bagua Grande", "Utcubamba"],
        "Áncash": ["Huaraz", "Chimbote", "Nuevo Chimbote", "Casma", "Huarmey", "Carhuaz"],
        "Apurímac": ["Abancay", "Andahuaylas", "Chincheros", "Chalhuanca"],
        "Arequipa": ["Arequipa", "Camaná", "Mollendo", "Majes", "Mejía"],
        "Ayacucho": ["Ayacucho", "Huanta", "San Juan Bautista", "Carmen Alto"],
        "Cajamarca": ["Cajamarca", "Jaén", "Chota", "Cutervo", "Celendín", "Bambamarca"],
        "Callao": ["Callao", "Ventanilla", "Bellavista", "La Perla", "Carmen de la Legua"],
        "Cusco": ["Cusco", "Sicuani", "Quillabamba", "Wanchaq", "Santiago", "San Sebastián"],
        "Huancavelica": ["Huancavelica", "Pampas", "Lircay", "Acobamba"],
        "Huánuco": ["Huánuco", "Tingo María", "Ambo", "La Unión"],
        "Ica": ["Ica", "Chincha Alta", "Pisco", "Nazca", "Palpa"],
        "Junín": ["Huancayo", "Tarma", "La Oroya", "Jauja", "Satipo", "Chanchamayo"],
        "La Libertad": ["Trujillo", "Chepén", "Pacasmayo", "Huamachuco", "Otuzco", "Virú"],
        "Lambayeque": ["Chiclayo", "Lambayeque", "Ferreñafe", "José Leonardo Ortiz", "La Victoria", "Pimentel"],
        "Lima": ["Lima", "San Juan de Lurigancho", "San Martín de Porres", "Comas", "Ate", "Villa El Salvador", "San Juan de Miraflores", "Los Olivos", "Miraflores", "San Isidro", "Surco", "La Molina"],
        "Loreto": ["Iquitos", "Yurimaguas", "Nauta", "Requena", "Contamana"],
        "Madre de Dios": ["Puerto Maldonado", "Tambopata", "Manu"],
        "Moquegua": ["Moquegua", "Ilo", "Samegua", "Torata"],
        "Pasco": ["Cerro de Pasco", "Oxapampa", "Villa Rica", "Yanahuanca"],
        "Piura": ["Piura", "Sullana", "Talara", "Paita", "Catacaos", "Sechura"],
        "Puno": ["Puno", "Juliaca", "Ayaviri", "Ilave", "Azángaro", "Yunguyo"],
        "San Martín": ["Moyobamba", "Tarapoto", "Rioja", "Juanjuí", "Tocache"],
        "Tacna": ["Tacna", "Alto de la Alianza", "Calana", "Pocollay"],
        "Tumbes": ["Tumbes", "Aguas Verdes", "Zarumilla", "Corrales"],
        "Ucayali": ["Pucallpa", "Aguaytía", "Campo Verde", "Manantay"],
    },
    "Ecuador": {
        "Azuay": ["Cuenca", "Gualaceo", "Paute", "Santa Isabel", "Girón"],
        "Bolívar": ["Guaranda", "San Miguel", "Chillanes", "Caluma"],
        "Cañar": ["Azogues", "La Troncal", "Cañar", "Biblián"],
        "Carchi": ["Tulcán", "San Gabriel", "El Ángel", "Bolívar"],
        "Chimborazo": ["Riobamba", "Alausí", "Guano", "Colta", "Chunchi"],
        "Cotopaxi": ["Latacunga", "La Maná", "Salcedo", "Saquisilí", "Pujilí"],
        "El Oro": ["Machala", "Pasaje", "Santa Rosa", "Huaquillas", "El Guabo", "Zaruma"],
        "Esmeraldas": ["Esmeraldas", "Atacames", "Quinindé", "San Lorenzo", "Muisne"],
        "Galápagos": ["Puerto Baquerizo Moreno", "Puerto Ayora", "Puerto Villamil"],
        "Guayas": ["Guayaquil", "Durán", "Samborondón", "Milagro", "Daule", "Playas", "Naranjal", "El Triunfo"],
        "Imbabura": ["Ibarra", "Otavalo", "Antonio Ante", "Cotacachi", "Urcuquí"],
        "Loja": ["Loja", "Catamayo", "Macará", "Cariamanga", "Vilcabamba"],
        "Los Ríos": ["Babahoyo", "Quevedo", "Vinces", "Ventanas", "Buena Fe"],
        "Manabí": ["Portoviejo", "Manta", "Chone", "Jipijapa", "Montecristi", "Bahía de Caráquez", "El Carmen"],
        "Morona Santiago": ["Macas", "Gualaquiza", "Sucúa", "Palora"],
        "Napo": ["Tena", "Archidona", "El Chaco", "Quijos"],
        "Orellana": ["Francisco de Orellana", "Joya de los Sachas", "Loreto"],
        "Pastaza": ["Puyo", "Mera", "Santa Clara", "Arajuno"],
        "Pichincha": ["Quito", "Sangolquí", "Machachi", "Cayambe", "Pedro Vicente Maldonado", "Puerto Quito"],
        "Santa Elena": ["Santa Elena", "La Libertad", "Salinas"],
        "Santo Domingo": ["Santo Domingo de los Colorados", "La Concordia"],
        "Sucumbíos": ["Nueva Loja", "Shushufindi", "Lago Agrio", "Cuyabeno"],
        "Tungurahua": ["Ambato", "Baños de Agua Santa", "Pelileo", "Píllaro"],
        "Zamora Chinchipe": ["Zamora", "Yantzaza", "Zumba", "Yacuambi"],
    },
    "Venezuela": {
        "Amazonas": ["Puerto Ayacucho", "San Fernando de Atabapo", "Maroa"],
        "Anzoátegui": ["Barcelona", "Puerto La Cruz", "El Tigre", "Anaco", "Lechería"],
        "Apure": ["San Fernando de Apure", "Guasdualito", "Achaguas", "Elorza"],
        "Aragua": ["Maracay", "Turmero", "La Victoria", "Villa de Cura", "Cagua"],
        "Barinas": ["Barinas", "Socopó", "Ciudad Bolivia", "Santa Bárbara"],
        "Bolívar": ["Ciudad Guayana", "Ciudad Bolívar", "Upata", "Caicara del Orinoco", "Santa Elena de Uairén"],
        "Carabobo": ["Valencia", "Puerto Cabello", "Guacara", "Naguanagua", "San Diego", "Los Guayos"],
        "Cojedes": ["San Carlos", "Tinaquillo", "Tinaco", "El Baúl"],
        "Delta Amacuro": ["Tucupita", "Pedernales", "Sierra Imataca"],
        "Distrito Capital": ["Caracas"],
        "Falcón": ["Coro", "Punto Fijo", "Tucacas", "Chichiriviche", "Dabajuro"],
        "Guárico": ["San Juan de los Morros", "Calabozo", "Valle de la Pascua", "Zaraza", "Altagracia de Orituco"],
        "Lara": ["Barquisimeto", "Cabudare", "Carora", "El Tocuyo", "Quíbor"],
        "Mérida": ["Mérida", "El Vigía", "Ejido", "Tovar", "Mucuchíes"],
        "Miranda": ["Los Teques", "Guarenas", "Guatire", "Charallave", "Ocumare del Tuy", "Santa Teresa del Tuy"],
        "Monagas": ["Maturín", "Caripito", "Temblador", "Punta de Mata"],
        "Nueva Esparta": ["La Asunción", "Porlamar", "Juan Griego", "Pampatar", "El Valle del Espíritu Santo"],
        "Portuguesa": ["Guanare", "Acarigua", "Araure", "Turén", "Agua Blanca"],
        "Sucre": ["Cumaná", "Carúpano", "Güiria", "Cumanacoa"],
        "Táchira": ["San Cristóbal", "Táriba", "La Fría", "Rubio", "San Antonio del Táchira"],
        "Trujillo": ["Trujillo", "Valera", "Boconó", "Escuque", "Betijoque"],
        "Vargas": ["La Guaira", "Maiquetía", "Catia La Mar", "Macuto", "Caraballeda"],
        "Yaracuy": ["San Felipe", "Yaritagua", "Chivacoa", "Nirgua", "Cocorote"],
        "Zulia": ["Maracaibo", "Cabimas", "Ciudad Ojeda", "Machiques", "Santa Bárbara del Zulia", "San Francisco"],
    },
    "Panamá": {
        "Bocas del Toro": ["Bocas del Toro", "Changuinola", "Almirante", "Chiriquí Grande"],
        "Chiriquí": ["David", "Puerto Armuelles", "Bugaba", "Boquete", "Volcán", "Dolega"],
        "Coclé": ["Penonomé", "Aguadulce", "Antón", "La Pintada", "Natá"],
        "Colón": ["Colón", "Portobelo", "Sabanitas", "Gatún"],
        "Darién": ["La Palma", "Yaviza", "El Real de Santa María", "Metetí"],
        "Emberá-Wounaan": ["Unión Chocó", "Cémaco"],
        "Guna Yala": ["El Porvenir", "Ailigandí", "Cartí", "Playón Chico"],
        "Herrera": ["Chitré", "Los Pozos", "Parita", "Pesé", "Ocú"],
        "Los Santos": ["Las Tablas", "Guararé", "Pedasí", "Tonosí", "Los Santos"],
        "Ngäbe-Buglé": ["Chichica", "Llano Ñopo", "Hato Chamí"],
        "Panamá": ["Panamá", "San Miguelito", "Chepo", "Pacora", "La Chorrera", "Arraiján"],
        "Panamá Oeste": ["La Chorrera", "Arraiján", "Capira", "Chame", "San Carlos"],
        "Veraguas": ["Santiago", "Soná", "La Mesa", "Las Palmas", "Atalaya"],
    },
    "Costa Rica": {
        "Alajuela": ["Alajuela", "San Carlos", "Grecia", "San Ramón", "Palmares", "Atenas", "Naranjo"],
        "Cartago": ["Cartago", "Paraíso", "La Unión", "Turrialba", "Oreamuno", "El Guarco"],
        "Guanacaste": ["Liberia", "Nicoya", "Santa Cruz", "Cañas", "Tilarán", "La Cruz", "Carrillo"],
        "Heredia": ["Heredia", "Barva", "Santo Domingo", "Santa Bárbara", "San Rafael", "San Isidro", "Belén"],
        "Limón": ["Limón", "Pococí", "Siquirres", "Guácimo", "Talamanca", "Matina"],
        "Puntarenas": ["Puntarenas", "Esparza", "Golfito", "Osa", "Quepos", "Corredores", "Parrita"],
        "San José": ["San José", "Escazú", "Desamparados", "Goicoechea", "Santa Ana", "Moravia", "Tibás", "Curridabat", "Montes de Oca"],
    },
    "Guatemala": {
        "Alta Verapaz": ["Cobán", "San Pedro Carchá", "Tactic", "Chamelco", "Chisec"],
        "Baja Verapaz": ["Salamá", "Rabinal", "San Jerónimo", "Cubulco", "Purulhá"],
        "Chimaltenango": ["Chimaltenango", "Comalapa", "San Martín Jilotepeque", "Patzún", "Tecpán"],
        "Chiquimula": ["Chiquimula", "Esquipulas", "Jocotán", "Camotán", "Quezaltepeque"],
        "El Progreso": ["Guastatoya", "Morazán", "San Agustín Acasaguastlán", "Sanarate"],
        "Escuintla": ["Escuintla", "Santa Lucía Cotzumalguapa", "La Democracia", "Tiquisate", "Puerto San José"],
        "Guatemala": ["Ciudad de Guatemala", "Mixco", "Villa Nueva", "Petapa", "San Juan Sacatepéquez", "Chinautla", "Amatitlán"],
        "Huehuetenango": ["Huehuetenango", "La Democracia", "Chiantla", "Santa Cruz Barillas", "Jacaltenango"],
        "Izabal": ["Puerto Barrios", "Morales", "Livingston", "El Estor", "Los Amates"],
        "Jalapa": ["Jalapa", "San Pedro Pinula", "Monjas", "San Luis Jilotepeque"],
        "Jutiapa": ["Jutiapa", "Asunción Mita", "Jerez", "El Progreso", "Agua Blanca"],
        "Petén": ["Flores", "San Benito", "Santa Elena", "La Libertad", "Sayaxché"],
        "Quetzaltenango": ["Quetzaltenango", "Coatepeque", "Salcajá", "San Juan Ostuncalco", "Almolonga"],
        "Quiché": ["Santa Cruz del Quiché", "Chichicastenango", "Nebaj", "Joyabaj", "Uspantán"],
        "Retalhuleu": ["Retalhuleu", "San Sebastián", "Champerico", "San Martín Zapotitlán"],
        "Sacatepéquez": ["Antigua Guatemala", "Ciudad Vieja", "San Lucas Sacatepéquez", "Jocotenango", "Sumpango"],
        "San Marcos": ["San Marcos", "Malacatán", "Ayutla", "Tecún Umán", "San Pedro Sacatepéquez"],
        "Santa Rosa": ["Cuilapa", "Barberena", "Chiquimulilla", "Taxisco", "Nueva Santa Rosa"],
        "Sololá": ["Sololá", "Panajachel", "Santiago Atitlán", "San Lucas Tolimán", "San Pedro La Laguna"],
        "Suchitepéquez": ["Mazatenango", "San Antonio Suchitepéquez", "Chicacao", "Patulul", "Santo Tomás La Unión"],
        "Totonicapán": ["Totonicapán", "San Cristóbal Totonicapán", "San Francisco El Alto", "Momostenango"],
        "Zacapa": ["Zacapa", "Estanzuela", "Río Hondo", "Gualán", "Teculután"],
    },
    "Estados Unidos": {
        "Alabama": ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
        "Alaska": ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
        "Arizona": ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler", "Tempe", "Glendale"],
        "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
        "California": ["Los Angeles", "San Diego", "San Francisco", "San Jose", "Sacramento", "Fresno", "Oakland", "Long Beach", "Bakersfield", "Anaheim"],
        "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Boulder"],
        "Connecticut": ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
        "Delaware": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
        "Florida": ["Miami", "Jacksonville", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Fort Lauderdale", "Tallahassee"],
        "Georgia": ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Macon"],
        "Hawaii": ["Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu"],
        "Idaho": ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
        "Illinois": ["Chicago", "Aurora", "Naperville", "Rockford", "Joliet", "Springfield"],
        "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
        "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
        "Kansas": ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka"],
        "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
        "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
        "Maine": ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
        "Maryland": ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie"],
        "Massachusetts": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
        "Michigan": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing"],
        "Minnesota": ["Minneapolis", "Saint Paul", "Rochester", "Bloomington", "Duluth"],
        "Mississippi": ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
        "Missouri": ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
        "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
        "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
        "Nevada": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
        "New Hampshire": ["Manchester", "Nashua", "Concord", "Dover", "Rochester"],
        "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Trenton"],
        "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
        "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
        "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville"],
        "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
        "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
        "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
        "Oregon": ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Beaverton"],
        "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Reading", "Erie", "Harrisburg"],
        "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence"],
        "South Carolina": ["Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill"],
        "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
        "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
        "Texas": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi"],
        "Utah": ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy"],
        "Vermont": ["Burlington", "South Burlington", "Rutland", "Barre", "Montpelier"],
        "Virginia": ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria"],
        "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent"],
        "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
        "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
        "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
    },
    "Brasil": {
        "Acre": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá"],
        "Alagoas": ["Maceió", "Arapiraca", "Rio Largo", "Palmeira dos Índios"],
        "Amapá": ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque"],
        "Amazonas": ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari"],
        "Bahia": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna", "Juazeiro"],
        "Ceará": ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral"],
        "Distrito Federal": ["Brasília", "Ceilândia", "Taguatinga", "Samambaia", "Planaltina"],
        "Espírito Santo": ["Vitória", "Vila Velha", "Serra", "Cariacica", "Cachoeiro de Itapemirim"],
        "Goiás": ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia"],
        "Maranhão": ["São Luís", "Imperatriz", "São José de Ribamar", "Timon", "Caxias"],
        "Mato Grosso": ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra"],
        "Mato Grosso do Sul": ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã"],
        "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros"],
        "Pará": ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal", "Parauapebas"],
        "Paraíba": ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux"],
        "Paraná": ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais"],
        "Pernambuco": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista"],
        "Piauí": ["Teresina", "Parnaíba", "Picos", "Piripiri", "Floriano"],
        "Rio de Janeiro": ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Belford Roxo"],
        "Rio Grande do Norte": ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Ceará-Mirim"],
        "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí"],
        "Rondônia": ["Porto Velho", "Ji-Paraná", "Ariquemes", "Cacoal", "Vilhena"],
        "Roraima": ["Boa Vista", "Rorainópolis", "Caracaraí", "Alto Alegre"],
        "Santa Catarina": ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Criciúma"],
        "São Paulo": ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "Ribeirão Preto", "Sorocaba"],
        "Sergipe": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "São Cristóvão"],
        "Tocantins": ["Palmas", "Araguaína", "Gurupi", "Porto Nacional", "Paraíso do Tocantins"],
    },
    "Francia": {
        "Auvergne-Rhône-Alpes": ["Lyon", "Saint-Étienne", "Grenoble", "Villeurbanne", "Clermont-Ferrand", "Annecy"],
        "Bourgogne-Franche-Comté": ["Dijon", "Besançon", "Belfort", "Chalon-sur-Saône", "Auxerre"],
        "Bretagne": ["Rennes", "Brest", "Quimper", "Lorient", "Vannes", "Saint-Malo"],
        "Centre-Val de Loire": ["Tours", "Orléans", "Bourges", "Blois", "Chartres"],
        "Corse": ["Ajaccio", "Bastia", "Porto-Vecchio", "Corte"],
        "Grand Est": ["Strasbourg", "Reims", "Metz", "Mulhouse", "Nancy", "Colmar"],
        "Hauts-de-France": ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkerque", "Calais"],
        "Île-de-France": ["París", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil", "Versailles", "Nanterre"],
        "Normandie": ["Rouen", "Le Havre", "Caen", "Cherbourg", "Évreux"],
        "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Poitiers", "Pau", "La Rochelle", "Biarritz"],
        "Occitanie": ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers", "Narbonne"],
        "Pays de la Loire": ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "La Roche-sur-Yon"],
        "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon", "Cannes", "Antibes"],
    },
    "Reino Unido": {
        "England": ["Londres", "Birmingham", "Manchester", "Leeds", "Liverpool", "Newcastle", "Sheffield", "Bristol", "Nottingham", "Southampton"],
        "Scotland": ["Edimburgo", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling"],
        "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry"],
        "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry", "Bangor"],
    },
    "Alemania": {
        "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg", "Ulm"],
        "Bayern": ["Múnich", "Núremberg", "Augsburgo", "Ratisbona", "Würzburgo", "Ingolstadt"],
        "Berlin": ["Berlín"],
        "Brandenburg": ["Potsdam", "Cottbus", "Brandenburg an der Havel", "Frankfurt (Oder)"],
        "Bremen": ["Bremen", "Bremerhaven"],
        "Hamburg": ["Hamburgo"],
        "Hessen": ["Fráncfort del Meno", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"],
        "Mecklenburg-Vorpommern": ["Rostock", "Schwerin", "Neubrandenburg", "Stralsund", "Greifswald"],
        "Niedersachsen": ["Hanóver", "Braunschweig", "Oldenburg", "Osnabrück", "Wolfsburgo", "Gotinga"],
        "Nordrhein-Westfalen": ["Colonia", "Düsseldorf", "Dortmund", "Essen", "Duisburgo", "Bochum", "Wuppertal", "Bonn"],
        "Rheinland-Pfalz": ["Maguncia", "Ludwigshafen", "Coblenza", "Tréveris", "Kaiserslautern"],
        "Saarland": ["Saarbrücken", "Neunkirchen", "Homburg", "Völklingen"],
        "Sachsen": ["Leipzig", "Dresde", "Chemnitz", "Zwickau", "Plauen"],
        "Sachsen-Anhalt": ["Halle", "Magdeburgo", "Dessau", "Wittenberg"],
        "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburgo", "Neumünster"],
        "Thüringen": ["Erfurt", "Jena", "Gera", "Weimar", "Gotha"],
    },
    "Italia": {
        "Abruzzo": ["L'Aquila", "Pescara", "Chieti", "Teramo"],
        "Basilicata": ["Potenza", "Matera"],
        "Calabria": ["Catanzaro", "Reggio Calabria", "Cosenza", "Crotone", "Vibo Valentia"],
        "Campania": ["Nápoles", "Salerno", "Caserta", "Avellino", "Benevento"],
        "Emilia-Romaña": ["Bolonia", "Parma", "Módena", "Reggio Emilia", "Rávena", "Ferrara", "Rímini"],
        "Friuli Venecia Julia": ["Trieste", "Udine", "Pordenone", "Gorizia"],
        "Lacio": ["Roma", "Latina", "Frosinone", "Viterbo", "Rieti"],
        "Liguria": ["Génova", "La Spezia", "Savona", "Imperia", "Sanremo"],
        "Lombardía": ["Milán", "Bérgamo", "Brescia", "Monza", "Como", "Varese", "Pavía"],
        "Marcas": ["Ancona", "Pesaro", "Fano", "Macerata", "Ascoli Piceno"],
        "Molise": ["Campobasso", "Isernia", "Termoli"],
        "Piamonte": ["Turín", "Novara", "Alessandria", "Asti", "Cuneo"],
        "Apulia": ["Bari", "Taranto", "Foggia", "Lecce", "Brindisi", "Andria"],
        "Cerdeña": ["Cagliari", "Sassari", "Quartu Sant'Elena", "Olbia", "Alghero"],
        "Sicilia": ["Palermo", "Catania", "Mesina", "Siracusa", "Ragusa", "Trapani"],
        "Toscana": ["Florencia", "Prato", "Livorno", "Arezzo", "Pisa", "Siena", "Lucca"],
        "Trentino-Alto Adigio": ["Trento", "Bolzano", "Merano", "Rovereto"],
        "Umbría": ["Perugia", "Terni", "Foligno", "Città di Castello"],
        "Valle de Aosta": ["Aosta", "Saint-Vincent", "Sarre"],
        "Véneto": ["Venecia", "Verona", "Padua", "Vicenza", "Treviso", "Rovigo"],
    },
    "Portugal": {
        "Aveiro": ["Aveiro", "Santa Maria da Feira", "Ovar", "Oliveira de Azeméis", "Ílhavo"],
        "Beja": ["Beja", "Moura", "Serpa", "Castro Verde"],
        "Braga": ["Braga", "Guimarães", "Famalicão", "Barcelos", "Vila Verde"],
        "Bragança": ["Bragança", "Mirandela", "Macedo de Cavaleiros", "Chaves"],
        "Castelo Branco": ["Castelo Branco", "Covilhã", "Fundão", "Sertã"],
        "Coimbra": ["Coimbra", "Figueira da Foz", "Cantanhede", "Montemor-o-Velho"],
        "Évora": ["Évora", "Estremoz", "Reguengos de Monsaraz", "Vendas Novas"],
        "Faro": ["Faro", "Portimão", "Loulé", "Albufeira", "Lagos", "Olhão", "Silves", "Tavira"],
        "Guarda": ["Guarda", "Seia", "Gouveia", "Pinhel"],
        "Leiria": ["Leiria", "Caldas da Rainha", "Marinha Grande", "Pombal", "Alcobaça"],
        "Lisboa": ["Lisboa", "Sintra", "Cascais", "Loures", "Amadora", "Almada", "Oeiras", "Setúbal"],
        "Portalegre": ["Portalegre", "Elvas", "Ponte de Sor", "Campo Maior"],
        "Porto": ["Porto", "Vila Nova de Gaia", "Matosinhos", "Maia", "Gondomar", "Santa Maria da Feira"],
        "Santarém": ["Santarém", "Tomar", "Torres Novas", "Ourém", "Abrantes"],
        "Setúbal": ["Setúbal", "Almada", "Seixal", "Barreiro", "Montijo", "Moita"],
        "Viana do Castelo": ["Viana do Castelo", "Ponte de Lima", "Arcos de Valdevez", "Caminha"],
        "Vila Real": ["Vila Real", "Chaves", "Peso da Régua", "Lamego"],
        "Viseu": ["Viseu", "Tondela", "Mangualde", "Nelas", "Santa Comba Dão"],
        "Açores": ["Ponta Delgada", "Angra do Heroísmo", "Horta", "Ribeira Grande"],
        "Madeira": ["Funchal", "Câmara de Lobos", "Santa Cruz", "Machico"],
    },
}


def get_states_for_country(country: str) -> list:
    """Obtiene la lista de estados/departamentos para un país"""
    if country in GEOGRAPHY_DATA:
        return sorted(GEOGRAPHY_DATA[country].keys())
    return []


def get_cities_for_state(country: str, state: str) -> list:
    """Obtiene la lista de ciudades para un estado/departamento"""
    if country in GEOGRAPHY_DATA and state in GEOGRAPHY_DATA[country]:
        return sorted(GEOGRAPHY_DATA[country][state])
    return []


def get_state_choices(country: str = None) -> list:
    """
    Genera choices para el campo state.
    Si se especifica un país, solo retorna los estados de ese país.
    """
    choices = [("", "Seleccionar...")]

    if country and country in GEOGRAPHY_DATA:
        for state in sorted(GEOGRAPHY_DATA[country].keys()):
            choices.append((state, state))
    else:
        # Todos los estados de todos los países
        all_states = set()
        for country_data in GEOGRAPHY_DATA.values():
            all_states.update(country_data.keys())
        for state in sorted(all_states):
            choices.append((state, state))

    return choices


def get_city_choices(country: str = None, state: str = None) -> list:
    """
    Genera choices para el campo city.
    Si se especifica país y estado, solo retorna las ciudades de ese estado.
    """
    choices = [("", "Seleccionar...")]

    if country and state and country in GEOGRAPHY_DATA:
        if state in GEOGRAPHY_DATA[country]:
            for city in sorted(GEOGRAPHY_DATA[country][state]):
                choices.append((city, city))
    else:
        # Todas las ciudades
        all_cities = set()
        for country_data in GEOGRAPHY_DATA.values():
            for cities in country_data.values():
                all_cities.update(cities)
        for city in sorted(all_cities):
            choices.append((city, city))

    return choices
