# Generated by Django 6.0 on 2025-12-30 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_businesshours_nullable_times'),
        ('core', '0007_add_password_set_token'),
        ('ecommerce', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Suma de todos los items (sin IVA)', max_digits=10, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.21'), help_text='Ej: 0.21 para 21%', max_digits=5, verbose_name='Tasa de IVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del IVA')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('billing_name', models.CharField(max_length=200, verbose_name='Nombre de facturación')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Email de facturación')),
                ('billing_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('billing_address', models.TextField(blank=True, verbose_name='Dirección de facturación')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('billing_country', models.CharField(default='ES', max_length=2, verbose_name='País')),
                ('shipping_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de envío')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Dirección de envío')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad de envío')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal de envío')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('product_name', models.CharField(max_length=300, verbose_name='Nombre del producto')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product', verbose_name='Producto')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Item de Orden (Producto)',
                'verbose_name_plural': 'Items de Orden (Productos)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('service_name', models.CharField(max_length=300, verbose_name='Nombre del servicio')),
                ('service_duration', models.IntegerField(verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('staff_member_name', models.CharField(max_length=200, verbose_name='Profesional')),
                ('appointment_datetime', models.DateTimeField(verbose_name='Fecha y hora de la cita')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='bookings.appointment', verbose_name='Cita')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='orders.order', verbose_name='Orden')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Servicio')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Item de Orden (Servicio)',
                'verbose_name_plural': 'Items de Orden (Servicios)',
                'ordering': ['appointment_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('transfer', 'Transferencia'), ('cash', 'Efectivo')], default='stripe', max_length=20, verbose_name='Método de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del pago', verbose_name='Metadata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Orden')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer'], name='orders_orde_tenant__37988c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status'], name='orders_orde_tenant__291115_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'order'], name='orders_orde_tenant__1e7123_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderserviceitem',
            index=models.Index(fields=['tenant', 'order'], name='orders_orde_tenant__686a21_idx'),
        ),
        migrations.AddIndex(
            model_name='orderserviceitem',
            index=models.Index(fields=['appointment'], name='orders_orde_appoint_c73209_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'order'], name='orders_paym_tenant__48261b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='orders_paym_stripe__40efb1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='orders_paym_status_83f434_idx'),
        ),
    ]
