# Generated by Django 5.1.7 on 2026-05-28 03:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentgateway_and_payment_updates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentgateway',
            name='orders_paym_tenant__idx_gw_cre',
        ),
        migrations.RenameIndex(
            model_name='paymentgateway',
            new_name='orders_paym_tenant__e36028_idx',
            old_name='orders_paym_tenant__idx_gw_prov',
        ),
        migrations.RenameIndex(
            model_name='paymentgateway',
            new_name='orders_paym_tenant__48ca78_idx',
            old_name='orders_paym_tenant__idx_gw_act',
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='CO', max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.19'), help_text='Ej: 0.19 para 19%', max_digits=5, verbose_name='Tasa de IVA'),
        ),
    ]
