# Generated by Django 5.1.7 on 2026-02-07 18:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0018_unify_subscription_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='Número de factura (ej: INV-2024-001)', max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal_plan', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cargo por plan', max_digits=12)),
                ('subtotal_extras', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cargo por extras fijos (empleados adicionales)', max_digits=12)),
                ('subtotal_usage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cargo por uso adicional (pay-as-you-go)', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Descuento aplicado', max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='IVA u otros impuestos', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total a pagar', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('paid', 'Pagada'), ('failed', 'Pago Fallido'), ('void', 'Anulada'), ('refunded', 'Reembolsada')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Fecha de emisión', null=True)),
                ('due_at', models.DateTimeField(blank=True, help_text='Fecha de vencimiento', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha de pago', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Método de pago usado', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Referencia de la transacción de pago', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único del plan (ej: starter, pro)', unique=True)),
                ('name', models.CharField(help_text='Nombre visible del plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del plan para mostrar al cliente')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Precio mensual en COP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio anual en COP (opcional, con descuento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('included_appointments', models.PositiveIntegerField(default=50, help_text='Citas incluidas por mes (0 = ilimitado)')),
                ('included_employees', models.PositiveIntegerField(default=1, help_text='Empleados incluidos (0 = ilimitado)')),
                ('included_sms', models.PositiveIntegerField(default=0, help_text='SMS incluidos por mes')),
                ('included_whatsapp', models.PositiveIntegerField(default=0, help_text='Mensajes WhatsApp incluidos por mes')),
                ('included_products', models.PositiveIntegerField(default=50, help_text='Productos en catálogo (0 = ilimitado)')),
                ('included_services', models.PositiveIntegerField(default=10, help_text='Servicios configurables (0 = ilimitado)')),
                ('extra_appointment_price', models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Precio por cita adicional', max_digits=8)),
                ('extra_employee_price', models.DecimalField(decimal_places=2, default=Decimal('29000.00'), help_text='Precio por empleado adicional (mensual)', max_digits=8)),
                ('extra_sms_price', models.DecimalField(decimal_places=2, default=Decimal('180.00'), help_text='Precio por SMS adicional', max_digits=8)),
                ('extra_whatsapp_price', models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text='Precio por mensaje WhatsApp adicional', max_digits=8)),
                ('has_analytics', models.BooleanField(default=False, help_text='Acceso a analytics avanzados')),
                ('has_api_access', models.BooleanField(default=False, help_text='Acceso a API')),
                ('has_custom_domain', models.BooleanField(default=False, help_text='Dominio personalizado')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Soporte prioritario')),
                ('has_white_label', models.BooleanField(default=False, help_text='Sin branding de GRAVITI')),
                ('is_active', models.BooleanField(default=True, help_text='¿Plan disponible para nuevas suscripciones?')),
                ('is_public', models.BooleanField(default=True, help_text='¿Visible en la página de precios?')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la página de precios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('plan', 'Plan'), ('extra_employee', 'Empleado Adicional'), ('usage_appointment', 'Citas Adicionales'), ('usage_sms', 'SMS Adicionales'), ('usage_whatsapp', 'WhatsApp Adicionales'), ('discount', 'Descuento'), ('tax', 'Impuesto')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de inicio de la suscripción')),
                ('current_period_start', models.DateTimeField(help_text='Inicio del período de facturación actual')),
                ('current_period_end', models.DateTimeField(help_text='Fin del período de facturación actual')),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Fecha de fin del período de prueba', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Fecha de cancelación (si aplica)', null=True)),
                ('status', models.CharField(choices=[('trial', 'Período de Prueba'), ('active', 'Activa'), ('past_due', 'Pago Pendiente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('extra_employees', models.PositiveIntegerField(default=0, help_text='Empleados adicionales contratados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('appointment', 'Cita'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('employee', 'Empleado')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad usada')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField(help_text='Inicio del período de facturación')),
                ('period_end', models.DateField(help_text='Fin del período de facturación')),
                ('object_id', models.CharField(blank=True, help_text='ID del objeto relacionado', max_length=100)),
                ('is_billable', models.BooleanField(default=True, help_text='¿Se debe cobrar? (False si está dentro del límite incluido)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario al momento del registro', max_digits=8, null=True)),
                ('description', models.CharField(blank=True, help_text="Descripción del uso (ej: 'Cita #123 - Juan Pérez')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('invoice', models.ForeignKey(blank=True, help_text='Factura donde se cobró este uso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='billing.invoice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['subscription', 'resource', 'period_start'], name='billing_usa_subscri_85c017_idx'), models.Index(fields=['subscription', 'period_start', 'period_end'], name='billing_usa_subscri_9623fb_idx')],
            },
        ),
    ]
