# Generated by Django 5.1.7 on 2026-02-07 18:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_initial_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='annual_discount_months',
            field=models.PositiveIntegerField(default=2, help_text='Meses gratis al pagar anual. Ej: 2 = paga 10 meses, recibe 12', verbose_name='Meses de descuento (plan anual)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del plan para mostrar al cliente', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_appointment_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Precio por cita adicional', max_digits=8, verbose_name='Precio cita extra'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_employee_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('29000.00'), help_text='Precio por empleado adicional (mensual)', max_digits=8, verbose_name='Precio empleado extra'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_sms_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('180.00'), help_text='Precio por SMS adicional', max_digits=8, verbose_name='Precio SMS extra'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_whatsapp_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text='Precio por mensaje WhatsApp adicional', max_digits=8, verbose_name='Precio WhatsApp extra'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_analytics',
            field=models.BooleanField(default=False, help_text='Acceso a analytics avanzados', verbose_name='Analytics avanzados'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_api_access',
            field=models.BooleanField(default=False, help_text='Acceso a API', verbose_name='Acceso a API'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_custom_domain',
            field=models.BooleanField(default=False, help_text='Dominio personalizado', verbose_name='Dominio personalizado'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False, help_text='Soporte prioritario', verbose_name='Soporte prioritario'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_white_label',
            field=models.BooleanField(default=False, help_text='Sin branding de GRAVITI', verbose_name='Sin branding (White Label)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_appointments',
            field=models.PositiveIntegerField(default=50, help_text='Citas incluidas por mes (0 = ilimitado)', verbose_name='Citas incluidas'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_employees',
            field=models.PositiveIntegerField(default=1, help_text='Empleados incluidos (0 = ilimitado)', verbose_name='Empleados incluidos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_products',
            field=models.PositiveIntegerField(default=50, help_text='Productos en catálogo (0 = ilimitado)', verbose_name='Productos incluidos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_services',
            field=models.PositiveIntegerField(default=10, help_text='Servicios configurables (0 = ilimitado)', verbose_name='Servicios incluidos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_sms',
            field=models.PositiveIntegerField(default=0, help_text='SMS incluidos por mes', verbose_name='SMS incluidos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_whatsapp',
            field=models.PositiveIntegerField(default=0, help_text='Mensajes WhatsApp incluidos por mes', verbose_name='WhatsApp incluidos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Plan disponible para nuevas suscripciones?', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='¿Visible en la página de precios?', verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio mensual en COP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio Mensual'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Nombre visible del plan', max_length=100, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(help_text='Se genera automáticamente a partir del nombre', unique=True, verbose_name='Identificador (slug)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la página de precios', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Se calcula automáticamente: Mensual × (12 - meses descuento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio Anual (calculado)'),
        ),
    ]
