# Generated by Django 5.1.7 on 2026-02-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_annual_discount_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='includes_bookings',
            field=models.BooleanField(default=False, help_text='Servicios agendables, Staff, Citas, Horarios', verbose_name='Incluye Reservas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_marketing',
            field=models.BooleanField(default=False, help_text='Cupones, Promociones, Reseñas, Banners', verbose_name='Incluye Marketing'),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_services',
            field=models.BooleanField(default=False, help_text='Servicios vendibles (planes, seguros, membresías)', verbose_name='Incluye Planes/Contratos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_shop',
            field=models.BooleanField(default=False, help_text='Productos, Categorías, Inventario, Órdenes, Carritos', verbose_name='Incluye Tienda'),
        ),
    ]
