# Generated by Django 5.1.7 on 2026-02-12 02:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_seed_initial_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order'], 'verbose_name': '[DEPRECATED] Plan', 'verbose_name_plural': '[DEPRECATED] Planes'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Descuento aplicado', max_digits=12, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal_extras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cargo por extras fijos (empleados adicionales)', max_digits=12, verbose_name='Cargo extras'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cargo por uso adicional (pay-as-you-go)', max_digits=12, verbose_name='Cargo uso'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='IVA u otros impuestos', max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total a pagar', max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='annual_discount_months',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_appointment_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_employee_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('29000.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_sms_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extra_whatsapp_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_white_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_appointments',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_employees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_products',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_services',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_sms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_whatsapp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='includes_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='includes_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='includes_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='includes_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Período de facturación'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de cancelación (si aplica)', null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(help_text='Fin del período de facturación actual', verbose_name='Fin del período'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(help_text='Inicio del período de facturación actual', verbose_name='Inicio del período'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='extra_employees',
            field=models.PositiveIntegerField(default=0, help_text='Empleados adicionales contratados', verbose_name='Empleados adicionales'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Usar módulos en su lugar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de inicio de la suscripción', verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de Prueba'), ('active', 'Activa'), ('past_due', 'Pago Pendiente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de fin del período de prueba', null=True, verbose_name='Fin del trial'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del uso', max_length=255),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='¿Se debe cobrar?'),
        ),
    ]
