# Generated by Django 5.1.7 on 2026-02-12 02:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_plan_options_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingconfig',
            options={'verbose_name': 'Configuración Global', 'verbose_name_plural': 'Configuración Global'},
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='base_annual_discount_months',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='base_monthly_price',
        ),
        migrations.AddField(
            model_name='module',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Fecha desde la cual aplica este precio', null=True, verbose_name='Fecha de vigencia'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Si es True, este módulo es requerido para todas las suscripciones (GRAVITI Web)', verbose_name='Es módulo base'),
        ),
        migrations.AddField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0', help_text='Versión del plan (ej: 1.0, 2.0)', max_length=20, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='module',
            name='annual_discount_months',
            field=models.PositiveIntegerField(default=2, help_text='Meses gratis al pagar anual (ej: 2 = paga 10 meses)', verbose_name='Meses de descuento (anual)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio mensual en COP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio Mensual'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Nombre comercial del módulo', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(choices=[('web', 'GRAVITI Web'), ('shop', 'GRAVITI Shop'), ('bookings', 'GRAVITI Bookings'), ('services', 'GRAVITI Services'), ('marketing', 'GRAVITI Marketing')], help_text='Identificador único del módulo', unique=True, verbose_name='Identificador'),
        ),
    ]
