# Generated by Django 5.1.7 on 2026-02-12 03:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_seed_graviti_web_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='included_storage_gb',
            field=models.PositiveIntegerField(default=0, help_text='GB de almacenamiento incluidos (0 = no aplica)', verbose_name='Almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='extra_storage_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Precio mensual por GB adicional de almacenamiento', max_digits=8, verbose_name='Precio GB extra'),
        ),
    ]
