# Generated by Django 5.1.7 on 2026-02-12 03:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='extra_appointment_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por cita adicional (0 = no aplica)', max_digits=8, verbose_name='Precio cita extra'),
        ),
        migrations.AddField(
            model_name='module',
            name='extra_employee_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio mensual por empleado adicional (0 = no aplica)', max_digits=8, verbose_name='Precio empleado extra'),
        ),
        migrations.AddField(
            model_name='module',
            name='extra_product_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por producto adicional (0 = no aplica)', max_digits=8, verbose_name='Precio producto extra'),
        ),
        migrations.AddField(
            model_name='module',
            name='extra_sms_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por SMS adicional (0 = no aplica)', max_digits=8, verbose_name='Precio SMS extra'),
        ),
        migrations.AddField(
            model_name='module',
            name='extra_storage_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio mensual por GB adicional (0 = no aplica)', max_digits=8, verbose_name='Precio GB extra'),
        ),
        migrations.AddField(
            model_name='module',
            name='extra_whatsapp_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por mensaje WhatsApp adicional (0 = no aplica)', max_digits=8, verbose_name='Precio WhatsApp extra'),
        ),
    ]
