# Generated by Django 5.1.7 on 2026-02-12 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_extra_prices_to_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['sort_order', 'monthly_price'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='module',
            name='extra_ai_request_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por generación de IA adicional (0 = no aplica)', max_digits=8, verbose_name='Precio generación IA extra'),
        ),
        migrations.AddField(
            model_name='module',
            name='included_ai_requests',
            field=models.PositiveIntegerField(default=0, help_text='Generaciones de IA incluidas por mes (para crear/editar sitio web)', verbose_name='Generaciones IA incluidas'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='extra_ai_request_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Precio por generación de IA adicional (~$0.12 USD)', max_digits=8, verbose_name='Precio generación IA extra'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='line_type',
            field=models.CharField(choices=[('base', 'Web Base'), ('module', 'Módulo'), ('extra_employee', 'Empleado Adicional'), ('usage_appointment', 'Citas Adicionales'), ('usage_sms', 'SMS Adicionales'), ('usage_whatsapp', 'WhatsApp Adicionales'), ('usage_ai', 'Generaciones IA Adicionales'), ('discount', 'Descuento'), ('tax', 'Impuesto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='included_storage_gb',
            field=models.PositiveIntegerField(default=15, help_text='GB de almacenamiento incluidos (0 = no aplica)', verbose_name='Almacenamiento (GB)'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='resource',
            field=models.CharField(choices=[('appointment', 'Cita'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('employee', 'Empleado'), ('ai_request', 'Generación IA')], max_length=50),
        ),
    ]
