# Generated by Django 5.1.7 on 2026-02-12 12:51

from django.db import migrations
from decimal import Decimal


def update_web_module(apps, schema_editor):
    """
    Actualiza el módulo GRAVITI Web con:
    - 15GB de almacenamiento incluido
    - 100 generaciones de IA incluidas/mes
    - Precio de $500 COP por generación extra
    """
    Module = apps.get_model('billing', 'Module')

    try:
        web_module = Module.objects.get(slug='web')
        web_module.included_storage_gb = 15
        web_module.included_ai_requests = 100
        web_module.extra_ai_request_price = Decimal('500.00')
        web_module.save()
        print(f"✓ Módulo Web actualizado: 15GB storage, 100 AI requests/mes")
    except Module.DoesNotExist:
        print("⚠ Módulo 'web' no encontrado")


def reverse_update(apps, schema_editor):
    """Revertir los cambios."""
    Module = apps.get_model('billing', 'Module')

    try:
        web_module = Module.objects.get(slug='web')
        web_module.included_storage_gb = 1
        web_module.included_ai_requests = 0
        web_module.extra_ai_request_price = Decimal('0')
        web_module.save()
    except Module.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_add_ai_usage_fields'),
    ]

    operations = [
        migrations.RunPython(update_web_module, reverse_update),
    ]
