# Generated by Django 5.1.7 on 2026-02-17 18:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_update_web_module_ai_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='annual_extra_ai_request_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por generación de IA adicional en plan anual (0 = usa precio mensual)', max_digits=8, verbose_name='Precio generación IA extra (anual)'),
        ),
        migrations.AddField(
            model_name='module',
            name='annual_included_ai_requests',
            field=models.PositiveIntegerField(default=0, help_text='Generaciones de IA incluidas en plan anual por mes (0 = usa valor mensual)', verbose_name='Generaciones IA (plan anual)'),
        ),
        migrations.AddField(
            model_name='module',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='Días de prueba para nuevos tenants con este módulo', verbose_name='Días de trial'),
        ),
        migrations.AddField(
            model_name='module',
            name='trial_included_ai_requests',
            field=models.PositiveIntegerField(default=5, help_text='Generaciones de IA incluidas durante el período de prueba', verbose_name='Generaciones IA en trial'),
        ),
        migrations.AlterField(
            model_name='module',
            name='extra_ai_request_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por generación de IA adicional en plan mensual (0 = no aplica)', max_digits=8, verbose_name='Precio generación IA extra'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Si es True, este módulo es requerido para todas las suscripciones (Web)', verbose_name='Es módulo base'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(choices=[('web', 'Web'), ('shop', 'Shop'), ('bookings', 'Bookings'), ('services', 'Services'), ('marketing', 'Marketing')], help_text='Identificador único del módulo', unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='has_white_label',
            field=models.BooleanField(default=False, help_text='Sin branding de GRAVITIFY', verbose_name='Sin branding (White Label)'),
        ),
    ]
