# Generated by Django 5.1.7 on 2026-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_add_trial_annual_ai_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(choices=[('web', 'Web'), ('shop', 'Shop'), ('bookings', 'Bookings'), ('services', 'Services'), ('marketing', 'Marketing'), ('management', 'Management')], help_text='Identificador único del módulo', unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='module',
            name='trial_included_ai_requests',
            field=models.PositiveIntegerField(default=10, help_text='Generaciones de IA incluidas durante el período de prueba', verbose_name='Generaciones IA en trial'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='has_white_label',
            field=models.BooleanField(default=False, help_text='Sin branding de NERBIS', verbose_name='Sin branding (White Label)'),
        ),
    ]
