# Generated by Django 6.0 on 2025-12-30 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_businesshours_nullable_times'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_add_password_set_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del carrito (opcional)', null=True, verbose_name='Expira en')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('item_type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio/Cita')], max_length=20, verbose_name='Tipo de item')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('appointment', models.ForeignKey(blank=True, help_text='Solo para items de tipo servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='bookings.appointment', verbose_name='Cita asociada')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Carrito')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('product', 'service')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['tenant', 'user'], name='cart_cart_tenant__f44e77_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['tenant', 'cart'], name='cart_cartit_tenant__286037_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['content_type', 'object_id'], name='cart_cartit_content_598ed3_idx'),
        ),
    ]
