# Generated by Django 5.1.7 on 2026-02-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_add_has_services_to_tenant'),
        ('orders', '0002_order_coupon_order_coupon_code_order_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(help_text='Ej: Seguros, Planes Funerarios, Membresías', max_length=200, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(help_text='Se genera automáticamente del nombre', max_length=200, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría', verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (lucide-react)', max_length=50, verbose_name='Icono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/categories/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(help_text='Ej: Plan Funerario Premium, Seguro de Vida Familiar', max_length=200, verbose_name='Nombre del servicio')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug (URL)')),
                ('description', models.TextField(help_text='Descripción breve para listados', verbose_name='Descripción corta')),
                ('full_description', models.TextField(blank=True, help_text='Descripción detallada del servicio (soporta HTML)', verbose_name='Descripción completa')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de características incluidas en el plan', verbose_name='Características')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=10, verbose_name='Precio')),
                ('billing_period', models.CharField(choices=[('once', 'Pago único'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], default='once', max_length=20, verbose_name='Periodo de facturación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/services/', verbose_name='Imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('is_featured', models.BooleanField(default=False, help_text='Se muestra en la página principal', verbose_name='¿Destacado?')),
                ('max_contracts', models.PositiveIntegerField(blank=True, help_text='Límite de contratos activos (vacío = ilimitado)', null=True, verbose_name='Máximo de contratos')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='subscriptions.marketplacecategory', verbose_name='Categoría')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Plan de Servicio',
                'verbose_name_plural': 'Planes de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(help_text='Fecha en que inicia la vigencia del contrato', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en que expira el contrato (vacío si es vitalicio)', null=True, verbose_name='Fecha de fin')),
                ('next_billing_date', models.DateField(blank=True, help_text='Para servicios recurrentes', null=True, verbose_name='Próxima fecha de cobro')),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Precio pagado al momento de la compra', max_digits=10, verbose_name='Precio pagado')),
                ('notes', models.TextField(blank=True, help_text='Notas para uso interno del admin', verbose_name='Notas internas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_contracts', to='orders.order', verbose_name='Orden de compra')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='subscriptions.marketplaceplan', verbose_name='Plan de servicio')),
            ],
            options={
                'verbose_name': 'Contrato de Servicio',
                'verbose_name_plural': 'Contratos de Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketplacecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_subscriptions_category_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_subscriptions_plan_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='marketplacecontract',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='subscriptions_tenant__2d28fa_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacecontract',
            index=models.Index(fields=['tenant', 'status', 'next_billing_date'], name='subscriptions_tenant__9adb0a_idx'),
        ),
    ]
