# Generated by Django 5.1.7 on 2026-02-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_app_label'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketplacecontract',
            new_name='subscriptio_tenant__d827a9_idx',
            old_name='subscriptions_tenant__2d28fa_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplacecontract',
            new_name='subscriptio_tenant__b1cf76_idx',
            old_name='subscriptions_tenant__9adb0a_idx',
        ),
    ]
