# Generated by Django 5.1.7 on 2026-04-30 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del gasto'),
        ),
    ]
