# Generated by Django 5.1.7 on 2026-01-18 22:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_add_otp_token'),
        ('ecommerce', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(help_text='Ej: Dúo Glow: Limpieza + Peeling', max_length=300, verbose_name='Nombre de la promoción')),
                ('slug', models.SlugField(blank=True, max_length=320, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la promoción', verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, help_text='Texto breve para mostrar en cards (ej: 15% OFF al reservar juntos)', max_length=200, verbose_name='Descripción corta')),
                ('promotion_type', models.CharField(choices=[('bundle', 'Bundle (Paquete combinado)'), ('discount', 'Descuento porcentual'), ('fixed', 'Precio fijo')], default='discount', max_length=20, verbose_name='Tipo de promoción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto fijo')], default='percentage', max_length=20, verbose_name='Tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 15) o monto fijo (ej: 10.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor del descuento')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text="Solo para promociones de tipo 'Precio fijo'", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio fijo')),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo para aplicar la promoción', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Compra mínima')),
                ('max_uses', models.IntegerField(blank=True, help_text='Límite total de veces que se puede usar (vacío = sin límite)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Usos máximos')),
                ('max_uses_per_customer', models.IntegerField(blank=True, help_text='Límite por cliente (vacío = sin límite)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Usos máximos por cliente')),
                ('times_used', models.IntegerField(default=0, verbose_name='Veces usada')),
                ('start_date', models.DateTimeField(help_text='Cuándo comienza la promoción', verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(help_text='Cuándo termina la promoción', verbose_name='Fecha de fin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Imagen de la promoción')),
                ('badge_text', models.CharField(blank=True, help_text="Ej: '15% OFF', 'OFERTA', '2x1'", max_length=50, verbose_name='Texto del badge')),
                ('cta_text', models.CharField(default='Aprovechar oferta', help_text='Texto del call-to-action', max_length=100, verbose_name='Texto del botón')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar en sección de promociones destacadas', verbose_name='¿Es destacada?')),
                ('priority', models.IntegerField(default=0, help_text='Mayor número = más prioridad', verbose_name='Prioridad')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-priority', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('quantity', models.IntegerField(default=1, help_text='Cantidad de este item incluida en la promoción', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='ecommerce.product', verbose_name='Producto')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.promotion', verbose_name='Promoción')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='services.service', verbose_name='Servicio')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Item de Promoción',
                'verbose_name_plural': 'Items de Promoción',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['tenant', 'is_active'], name='promotions__tenant__0878f1_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='promotions__tenant__c62a84_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['tenant', 'is_featured'], name='promotions__tenant__b95a55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='promotionitem',
            index=models.Index(fields=['tenant', 'promotion'], name='promotions__tenant__b1c1e0_idx'),
        ),
    ]
