# Generated by Django 6.0 on 2025-12-27 16:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_uid_multi_tenant_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/categories/', verbose_name='Imagen de la categoría')),
                ('icon', models.CharField(blank=True, help_text="Nombre del icono (ej: 'spa', 'face', 'massage')", max_length=100, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('position', models.CharField(blank=True, help_text='Ej: Esteticista Senior, Masajista, etc.', max_length=200, verbose_name='Cargo')),
                ('bio', models.TextField(blank=True, help_text='Descripción profesional del empleado', verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='Foto')),
                ('is_available', models.BooleanField(default=True, help_text='Si está aceptando citas actualmente', verbose_name='¿Está disponible?')),
                ('accepts_new_clients', models.BooleanField(default=True, verbose_name='¿Acepta nuevos clientes?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar primero en listados', verbose_name='¿Es destacado?')),
                ('specialties', models.ManyToManyField(blank=True, help_text='Categorías en las que se especializa', related_name='specialists', to='services.servicecategory', verbose_name='Especialidades')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro del Staff',
                'verbose_name_plural': 'Miembros del Staff',
                'ordering': ['-is_featured', 'order', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre del servicio')),
                ('slug', models.SlugField(blank=True, max_length=320, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción completa')),
                ('duration_minutes', models.IntegerField(help_text='Duración del servicio en minutos (5-480)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('requires_deposit', models.BooleanField(default=False, help_text='Si requiere pago adelantado para reservar', verbose_name='¿Requiere depósito?')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto del depósito')),
                ('max_advance_booking_days', models.IntegerField(default=90, help_text='Cuántos días adelante se puede reservar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días máximos de anticipación')),
                ('min_advance_booking_hours', models.IntegerField(default=2, help_text='Cuántas horas antes se debe reservar', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas mínimas de anticipación')),
                ('is_active', models.BooleanField(default=True, help_text='Servicio visible para clientes', verbose_name='¿Está activo?')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar en servicios destacados', verbose_name='¿Es destacado?')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta título')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta descripción')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Categoría')),
                ('assigned_staff', models.ManyToManyField(blank=True, help_text='Empleados que pueden realizar este servicio', related_name='services', to='services.staffmember', verbose_name='Personal asignado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['tenant', 'is_active'], name='services_se_tenant__f1613a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['tenant', 'is_available'], name='services_st_tenant__5705b6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'is_active', 'category'], name='services_se_tenant__d7859c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'is_featured'], name='services_se_tenant__463bf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('tenant', 'slug')},
        ),
    ]
