# Generated by Django 5.1.7 on 2026-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del servicio (recomendado: 800x600px)', null=True, upload_to='services/images/', verbose_name='Imagen del servicio'),
        ),
    ]
