# Generated by Django 5.1.7 on 2026-01-29 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Rating promedio'),
        ),
        migrations.AddField(
            model_name='service',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de reviews'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating promedio'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de reviews'),
        ),
    ]
