name: "Task"
description: "Tarea técnica, refactor, o mejora interna"
labels: ["tipo: enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción de la tarea
      description: ¿Qué hay que hacer y por qué?
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Subtareas específicas
      value: |
        - [ ] Subtarea 1
        - [ ] Subtarea 2
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Módulo
      options:
        - Core / Auth
        - E-commerce
        - Bookings
        - Services
        - Orders / Pagos
        - Cart
        - Notifications
        - Subscriptions
        - Frontend
        - Mobile
        - Websites
        - Infra / CI/CD
    validations:
      required: true
