# Generated by Django 5.1.7 on 2026-01-27 13:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_add_otp_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('title', models.CharField(blank=True, help_text='Título breve de la review', max_length=200, verbose_name='Título')),
                ('comment', models.TextField(blank=True, help_text='Comentario detallado', verbose_name='Comentario')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='El usuario compró este producto/servicio', verbose_name='Compra verificada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderado en')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de rechazo')),
                ('business_response', models.TextField(blank=True, verbose_name='Respuesta del negocio')),
                ('business_response_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido en')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Votos útiles')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('product', 'service')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review', verbose_name='Review')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto Útil',
                'verbose_name_plural': 'Votos Útiles',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/', verbose_name='Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Review')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Imagen de Review',
                'verbose_name_plural': 'Imágenes de Reviews',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', 'content_type', 'object_id'], name='reviews_rev_tenant__29e542_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'created_at'], name='reviews_rev_status_c24b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('tenant', 'user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', 'user'], name='reviews_rev_review__c11ee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review', 'order'], name='reviews_rev_review__403fbd_idx'),
        ),
    ]
