# Generated by Django 5.1.7 on 2026-02-12 12:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0014_update_web_module_ai_values'),
        ('core', '0022_alter_tenant_options_alter_tenant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre visible del template (ej: 'Restaurante Moderno')", max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador único del template', max_length=100, unique=True, verbose_name='Slug')),
                ('industry', models.CharField(choices=[('restaurant', 'Restaurante / Café'), ('retail', 'Tienda / Retail'), ('beauty', 'Salón de Belleza / Spa'), ('health', 'Salud / Clínica'), ('fitness', 'Gimnasio / Fitness'), ('professional', 'Servicios Profesionales'), ('education', 'Educación / Academia'), ('automotive', 'Automotriz / Taller'), ('real_estate', 'Inmobiliaria'), ('events', 'Eventos / Catering'), ('pet', 'Mascotas / Veterinaria'), ('tech', 'Tecnología / Startup'), ('creative', 'Creativo / Agencia'), ('consulting', 'Consultoría'), ('generic', 'Negocio General')], default='generic', max_length=50, verbose_name='Industria')),
                ('description', models.TextField(help_text='Descripción del template para el usuario', verbose_name='Descripción')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/', verbose_name='Imagen de vista previa')),
                ('preview_url', models.URLField(blank=True, help_text='URL a un sitio de demostración de este template', verbose_name='URL de demo')),
                ('structure_schema', models.JSONField(default=dict, help_text='\n        Define las secciones del template. Ejemplo:\n        {\n            "sections": [\n                {"id": "hero", "name": "Encabezado Principal", "required": true},\n                {"id": "about", "name": "Sobre Nosotros", "required": false},\n                {"id": "services", "name": "Servicios", "required": false},\n                {"id": "gallery", "name": "Galería", "required": false},\n                {"id": "testimonials", "name": "Testimonios", "required": false},\n                {"id": "contact", "name": "Contacto", "required": true}\n            ]\n        }\n        ', verbose_name='Esquema de estructura')),
                ('ai_system_prompt', models.TextField(blank=True, help_text='\n        Instrucciones base para la IA al generar contenido para este template.\n        Incluye contexto de la industria, tono recomendado, etc.\n        ', verbose_name='Prompt del sistema para IA')),
                ('default_theme', models.JSONField(default=dict, help_text='\n        Configuración visual base. Ejemplo:\n        {\n            "primary_color": "#3b82f6",\n            "secondary_color": "#10b981",\n            "font_heading": "Poppins",\n            "font_body": "Inter",\n            "style": "modern"\n        }\n        ', verbose_name='Tema por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_premium', models.BooleanField(default=False, help_text='Los templates premium requieren módulos adicionales', verbose_name='Premium')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Template de Sitio Web',
                'verbose_name_plural': 'Templates de Sitio Web',
                'ordering': ['sort_order', 'industry', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('onboarding', 'En Onboarding'), ('generating', 'Generando con IA'), ('review', 'En Revisión'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='Estado')),
                ('content_data', models.JSONField(default=dict, help_text='Contenido de todas las secciones del sitio', verbose_name='Contenido del sitio')),
                ('theme_data', models.JSONField(default=dict, help_text='Colores, fuentes y estilos personalizados', verbose_name='Configuración del tema')),
                ('media_data', models.JSONField(default=dict, help_text='Referencias a imágenes y archivos del sitio', verbose_name='Media del sitio')),
                ('seo_data', models.JSONField(default=dict, help_text='Meta títulos, descripciones, keywords', verbose_name='Datos SEO')),
                ('custom_domain', models.CharField(blank=True, help_text='Dominio propio del cliente (requiere configuración DNS)', max_length=255, verbose_name='Dominio personalizado')),
                ('subdomain', models.SlugField(blank=True, help_text='Subdominio en graviti (ej: minegocio.graviti.co)', verbose_name='Subdominio')),
                ('ai_generations_count', models.PositiveIntegerField(default=0, help_text='Contador de generaciones de IA este mes', verbose_name='Generaciones IA usadas')),
                ('last_generation_at', models.DateTimeField(blank=True, null=True, verbose_name='Última generación')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_config', to='core.tenant', verbose_name='Tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='websites', to='websites.websitetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Configuración de Sitio Web',
                'verbose_name_plural': 'Configuraciones de Sitios Web',
            },
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('initial', 'Generación Inicial'), ('regenerate_section', 'Regenerar Sección'), ('edit_content', 'Editar Contenido'), ('generate_images', 'Generar Imágenes'), ('seo_optimization', 'Optimización SEO')], max_length=30, verbose_name='Tipo de generación')),
                ('section_id', models.CharField(blank=True, help_text='ID de la sección afectada', max_length=50, verbose_name='Sección')),
                ('prompt_summary', models.TextField(blank=True, help_text='Versión resumida del prompt usado (sin datos sensibles)', verbose_name='Resumen del prompt')),
                ('model_used', models.CharField(default='claude-3-haiku', help_text='Modelo de IA usado', max_length=50, verbose_name='Modelo usado')),
                ('tokens_input', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada')),
                ('tokens_output', models.PositiveIntegerField(default=0, verbose_name='Tokens de salida')),
                ('cost_estimated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Costo estimado (COP)')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('is_billable', models.BooleanField(default=False, help_text='True si excede el límite mensual incluido', verbose_name='Facturable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('billed_in_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_logs', to='core.tenant')),
                ('website_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='websites.websiteconfig')),
            ],
            options={
                'verbose_name': 'Registro de Generación IA',
                'verbose_name_plural': 'Registros de Generaciones IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.SlugField(help_text="Identificador único (ej: 'business_name', 'main_service')", verbose_name='Clave')),
                ('question_text', models.CharField(help_text='Texto que verá el usuario', max_length=255, verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('choice', 'Opción única'), ('multi_choice', 'Opción múltiple'), ('color', 'Selector de color'), ('image', 'Carga de imagen'), ('number', 'Número'), ('url', 'URL')], default='text', max_length=20, verbose_name='Tipo')),
                ('options', models.JSONField(blank=True, default=list, help_text='Lista de opciones. Ej: ["Opción 1", "Opción 2"]', verbose_name='Opciones')),
                ('placeholder', models.CharField(blank=True, help_text='Texto de ayuda dentro del campo', max_length=255, verbose_name='Placeholder')),
                ('help_text', models.TextField(blank=True, help_text='Explicación adicional debajo del campo', verbose_name='Texto de ayuda')),
                ('ai_context', models.TextField(blank=True, help_text='\n        Describe qué información aporta esta pregunta y cómo debe usarla la IA.\n        Ej: "Este es el nombre del negocio. Úsalo como título principal\n        y menciona el nombre en textos de bienvenida."\n        ', verbose_name='Contexto para IA')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('min_length', models.PositiveIntegerField(default=0, verbose_name='Longitud mínima')),
                ('max_length', models.PositiveIntegerField(default=500, verbose_name='Longitud máxima')),
                ('section', models.CharField(default='basic', help_text='Agrupa preguntas: basic, branding, content, contact', max_length=50, verbose_name='Sección')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('template', models.ForeignKey(blank=True, help_text='Dejar vacío para preguntas genéricas (todas las plantillas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='websites.websitetemplate')),
            ],
            options={
                'verbose_name': 'Pregunta de Onboarding',
                'verbose_name_plural': 'Preguntas de Onboarding',
                'ordering': ['section', 'sort_order'],
                'unique_together': {('template', 'question_key')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.JSONField(help_text='Valor de la respuesta en formato JSON', verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='websites.onboardingquestion')),
                ('website_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='websites.websiteconfig')),
            ],
            options={
                'verbose_name': 'Respuesta de Onboarding',
                'verbose_name_plural': 'Respuestas de Onboarding',
                'unique_together': {('website_config', 'question')},
            },
        ),
    ]
