# Generated by Django 5.1.7 on 2026-02-12

from django.db import migrations


def create_base_questions(apps, schema_editor):
    """
    Crea las preguntas base de onboarding que aplican a todos los templates.

    Estas preguntas son genéricas y capturan la información fundamental
    del negocio para que la IA pueda generar contenido personalizado.
    """
    OnboardingQuestion = apps.get_model('websites', 'OnboardingQuestion')

    # Sección: basic - Información básica del negocio
    basic_questions = [
        {
            'question_key': 'business_name',
            'question_text': '¿Cuál es el nombre de tu negocio?',
            'question_type': 'text',
            'placeholder': 'Ej: Salón de Belleza María',
            'help_text': 'Este será el nombre principal que aparecerá en tu sitio web.',
            'ai_context': 'Nombre del negocio. Usar como título principal, en el logo de texto, y mencionarlo en textos de bienvenida.',
            'is_required': True,
            'section': 'basic',
            'sort_order': 1,
        },
        {
            'question_key': 'business_tagline',
            'question_text': '¿Tienes un slogan o frase que describa tu negocio?',
            'question_type': 'text',
            'placeholder': 'Ej: Tu belleza, nuestra pasión',
            'help_text': 'Opcional. Una frase corta que capture la esencia de tu negocio.',
            'ai_context': 'Slogan del negocio. Si existe, usar como subtítulo del hero. Si no existe, la IA debe generar uno apropiado.',
            'is_required': False,
            'section': 'basic',
            'sort_order': 2,
        },
        {
            'question_key': 'business_description',
            'question_text': 'Describe brevemente tu negocio y lo que ofreces',
            'question_type': 'textarea',
            'placeholder': 'Cuéntanos sobre tu negocio, tus servicios principales y qué te hace especial...',
            'help_text': 'Esta información ayudará a crear el contenido de tu sitio.',
            'ai_context': 'Descripción del negocio proporcionada por el usuario. Usar como base para generar textos "Sobre Nosotros" y descripciones de servicios. Mantener el tono y estilo del usuario.',
            'is_required': True,
            'min_length': 50,
            'max_length': 1000,
            'section': 'basic',
            'sort_order': 3,
        },
        {
            'question_key': 'target_audience',
            'question_text': '¿Quiénes son tus clientes ideales?',
            'question_type': 'textarea',
            'placeholder': 'Ej: Mujeres profesionales de 25-45 años que buscan tratamientos de belleza de alta calidad...',
            'help_text': 'Describe a quién le hablas principalmente.',
            'ai_context': 'Audiencia objetivo del negocio. Usar para ajustar el tono del contenido y los mensajes de marketing.',
            'is_required': False,
            'section': 'basic',
            'sort_order': 4,
        },
        {
            'question_key': 'unique_selling_point',
            'question_text': '¿Qué hace diferente o especial a tu negocio?',
            'question_type': 'textarea',
            'placeholder': 'Ej: Más de 15 años de experiencia, productos orgánicos, atención personalizada...',
            'help_text': 'Tus ventajas competitivas o lo que te distingue.',
            'ai_context': 'Propuesta de valor única. Resaltar estos puntos en el contenido del hero, sección "Por qué elegirnos" y testimonios.',
            'is_required': False,
            'section': 'basic',
            'sort_order': 5,
        },
    ]

    # Sección: branding - Identidad visual
    branding_questions = [
        {
            'question_key': 'brand_tone',
            'question_text': '¿Qué tono de comunicación prefieres para tu sitio?',
            'question_type': 'choice',
            'options': [
                'Profesional y elegante',
                'Cálido y cercano',
                'Moderno y dinámico',
                'Minimalista y sofisticado',
                'Juvenil y fresco',
            ],
            'help_text': 'Esto definirá el estilo de los textos de tu sitio.',
            'ai_context': 'Tono de comunicación preferido. Ajustar el estilo de escritura según la opción seleccionada.',
            'is_required': True,
            'section': 'branding',
            'sort_order': 1,
        },
        {
            'question_key': 'primary_color',
            'question_text': '¿Cuál es el color principal de tu marca?',
            'question_type': 'color',
            'help_text': 'Si no tienes uno definido, podemos sugerirte opciones.',
            'ai_context': 'Color principal de la marca. Usar como color primario del tema.',
            'is_required': False,
            'section': 'branding',
            'sort_order': 2,
        },
        {
            'question_key': 'secondary_color',
            'question_text': '¿Tienes un segundo color para tu marca?',
            'question_type': 'color',
            'help_text': 'Opcional. Un color complementario.',
            'ai_context': 'Color secundario de la marca. Usar como color de acento.',
            'is_required': False,
            'section': 'branding',
            'sort_order': 3,
        },
        {
            'question_key': 'logo_upload',
            'question_text': '¿Tienes un logo para tu negocio?',
            'question_type': 'image',
            'help_text': 'Sube tu logo en formato PNG o SVG con fondo transparente.',
            'ai_context': 'Logo del negocio. Usar en el header del sitio.',
            'is_required': False,
            'section': 'branding',
            'sort_order': 4,
        },
    ]

    # Sección: content - Contenido específico
    content_questions = [
        {
            'question_key': 'main_services',
            'question_text': '¿Cuáles son tus servicios o productos principales?',
            'question_type': 'textarea',
            'placeholder': 'Ej: Corte de cabello, Tratamientos faciales, Manicure y pedicure, Masajes...',
            'help_text': 'Lista tus servicios principales, separados por comas o en líneas separadas.',
            'ai_context': 'Servicios principales del negocio. Usar para crear la sección de servicios y mencionar en el contenido general.',
            'is_required': True,
            'section': 'content',
            'sort_order': 1,
        },
        {
            'question_key': 'price_range',
            'question_text': '¿Quieres mostrar precios en tu sitio?',
            'question_type': 'choice',
            'options': [
                'Sí, mostrar precios exactos',
                'Mostrar rango de precios (desde $X)',
                'No mostrar precios, solo "Consultar"',
            ],
            'help_text': 'Decide cómo manejar la información de precios.',
            'ai_context': 'Estrategia de precios. Ajustar cómo se presentan los servicios según la opción.',
            'is_required': True,
            'section': 'content',
            'sort_order': 2,
        },
        {
            'question_key': 'gallery_images',
            'question_text': '¿Tienes fotos de tu negocio o trabajo para mostrar?',
            'question_type': 'multi_choice',
            'options': [
                'Fotos del local/establecimiento',
                'Fotos de trabajos realizados',
                'Fotos del equipo',
                'No tengo fotos aún',
            ],
            'help_text': 'Podrás subirlas después. Esto nos ayuda a planear las secciones.',
            'ai_context': 'Tipo de contenido visual disponible. Ajustar las secciones del sitio según lo disponible.',
            'is_required': False,
            'section': 'content',
            'sort_order': 3,
        },
        {
            'question_key': 'testimonials_available',
            'question_text': '¿Tienes testimonios o reseñas de clientes?',
            'question_type': 'choice',
            'options': [
                'Sí, tengo testimonios escritos',
                'Tengo reseñas en Google/redes sociales',
                'No tengo testimonios aún',
            ],
            'help_text': 'Los testimonios aumentan la confianza de nuevos clientes.',
            'ai_context': 'Disponibilidad de testimonios. Si no hay, la IA puede sugerir solicitar algunos.',
            'is_required': False,
            'section': 'content',
            'sort_order': 4,
        },
    ]

    # Sección: contact - Información de contacto
    contact_questions = [
        {
            'question_key': 'business_address',
            'question_text': '¿Cuál es la dirección de tu negocio?',
            'question_type': 'textarea',
            'placeholder': 'Calle, número, barrio, ciudad, país',
            'help_text': 'Dirección completa para mostrar en el sitio y en Google Maps.',
            'ai_context': 'Dirección física del negocio. Mostrar en la sección de contacto y en el footer.',
            'is_required': False,
            'section': 'contact',
            'sort_order': 1,
        },
        {
            'question_key': 'business_phone',
            'question_text': '¿Cuál es el teléfono de contacto?',
            'question_type': 'text',
            'placeholder': '+57 300 123 4567',
            'help_text': 'Teléfono principal para que los clientes te contacten.',
            'ai_context': 'Teléfono de contacto. Mostrar como link clicable.',
            'is_required': True,
            'section': 'contact',
            'sort_order': 2,
        },
        {
            'question_key': 'business_email',
            'question_text': '¿Cuál es el correo electrónico de contacto?',
            'question_type': 'text',
            'placeholder': 'contacto@minegocio.com',
            'help_text': 'Email donde recibirás consultas del sitio web.',
            'ai_context': 'Email de contacto. Mostrar en la sección de contacto.',
            'is_required': False,
            'section': 'contact',
            'sort_order': 3,
        },
        {
            'question_key': 'business_whatsapp',
            'question_text': '¿Tienes WhatsApp para atención al cliente?',
            'question_type': 'text',
            'placeholder': '+57 300 123 4567',
            'help_text': 'Número de WhatsApp para el botón de contacto directo.',
            'ai_context': 'WhatsApp del negocio. Agregar botón flotante de WhatsApp.',
            'is_required': False,
            'section': 'contact',
            'sort_order': 4,
        },
        {
            'question_key': 'business_hours',
            'question_text': '¿Cuál es tu horario de atención?',
            'question_type': 'textarea',
            'placeholder': 'Lunes a Viernes: 9am - 7pm\nSábados: 9am - 2pm\nDomingos: Cerrado',
            'help_text': 'Horario de atención para mostrar a los clientes.',
            'ai_context': 'Horario del negocio. Mostrar en la sección de contacto/footer.',
            'is_required': False,
            'section': 'contact',
            'sort_order': 5,
        },
        {
            'question_key': 'social_media',
            'question_text': '¿Qué redes sociales tiene tu negocio?',
            'question_type': 'multi_choice',
            'options': [
                'Instagram',
                'Facebook',
                'TikTok',
                'YouTube',
                'LinkedIn',
                'Pinterest',
            ],
            'help_text': 'Podrás agregar los enlaces después.',
            'ai_context': 'Redes sociales del negocio. Agregar iconos con links en el footer.',
            'is_required': False,
            'section': 'contact',
            'sort_order': 6,
        },
    ]

    # Crear todas las preguntas
    all_questions = basic_questions + branding_questions + content_questions + contact_questions

    for q_data in all_questions:
        OnboardingQuestion.objects.create(
            template=None,  # Genéricas, aplican a todos
            **q_data
        )

    print(f"✓ Creadas {len(all_questions)} preguntas de onboarding genéricas")


def reverse_questions(apps, schema_editor):
    """Elimina las preguntas genéricas."""
    OnboardingQuestion = apps.get_model('websites', 'OnboardingQuestion')
    OnboardingQuestion.objects.filter(template__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_questions, reverse_questions),
    ]
