# Generated by Django 5.1.7 on 2026-02-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_initial_onboarding_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente IA'), ('system', 'Sistema')], help_text='Quién envió el mensaje', max_length=20, verbose_name='Rol')),
                ('content', models.TextField(help_text='Contenido del mensaje', verbose_name='Contenido')),
                ('section_id', models.CharField(blank=True, help_text='ID de la sección que se estaba editando', max_length=50, verbose_name='Sección afectada')),
                ('changes_made', models.JSONField(blank=True, default=dict, help_text='Resumen de los cambios aplicados por este mensaje', verbose_name='Cambios realizados')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Tokens consumidos en esta interacción', verbose_name='Tokens usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('website_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='websites.websiteconfig', verbose_name='Configuración del sitio')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
