# Generated by Django 5.1.7 on 2026-02-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_update_templates_split_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='full_prompt',
            field=models.TextField(blank=True, help_text='System prompt + user prompt enviado a la IA', verbose_name='Prompt completo'),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='onboarding_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot de las respuestas del onboarding usadas en la generación', verbose_name='Datos del onboarding'),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='raw_response',
            field=models.TextField(blank=True, help_text='Texto completo devuelto por la IA antes de parsear', verbose_name='Respuesta cruda de la IA'),
        ),
    ]
