# Generated by Django 5.1.7 on 2026-04-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0014_add_published_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='generation_task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea Celery activa de generación', max_length=255, null=True, verbose_name='ID de tarea Celery'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='subdomain',
            field=models.SlugField(blank=True, help_text='Subdominio en nerbis (ej: minegocio.nerbis.com)', verbose_name='Subdominio'),
        ),
    ]
