# Generated by Django 5.1.7 on 2026-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_platformmodule'),
        ('websites', '0014_add_published_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestion',
            name='hint',
            field=models.CharField(blank=True, help_text='Texto de ayuda debajo del campo', max_length=200, verbose_name='Hint'),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='input_type',
            field=models.CharField(choices=[('textarea', 'Área de texto'), ('input', 'Campo de texto'), ('multiselect', 'Selección múltiple'), ('modules', 'Selector de módulos')], default='input', help_text='Tipo de componente en la interfaz de onboarding', max_length=20, verbose_name='Tipo de input UI'),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='message',
            field=models.CharField(blank=True, help_text='Lo que Pipe pregunta al usuario en el chat conversacional', max_length=300, verbose_name='Mensaje de Pipe'),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='required_modules',
            field=models.ManyToManyField(blank=True, help_text='Si vacío, la pregunta siempre se muestra. Si tiene módulos, solo si el usuario los seleccionó.', related_name='onboarding_questions', to='core.platformmodule', verbose_name='Módulos requeridos'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='subdomain',
            field=models.SlugField(blank=True, help_text='Subdominio en nerbis (ej: minegocio.nerbis.com)', verbose_name='Subdominio'),
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador ej: about', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Nombre visible ej: Sobre nosotros', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descripcion corta de la pagina', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono Lucide', max_length=50)),
                ('is_mandatory', models.BooleanField(default=False, help_text='No se puede quitar (Home, Contacto)')),
                ('is_default', models.BooleanField(default=False, help_text='Preseleccionada en onboarding')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden de la pagina en el listado')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta disponible para seleccion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_include_modules', models.ManyToManyField(blank=True, help_text='Se incluye automaticamente si el usuario selecciona estos modulos', related_name='auto_pages', to='core.platformmodule')),
            ],
            options={
                'verbose_name': 'Pagina de sitio web',
                'verbose_name_plural': 'Paginas de sitio web',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
