# Generated by Django 5.1.7 on 2026-05-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0015_onboardingquestion_hint_and_more'),
        ('websites', '0015_websiteconfig_generation_task_id_and_more'),
    ]

    operations = [
    ]
