# Generated by Django 5.1.7 on 2026-05-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0016_merge_20260520_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingquestion',
            name='input_type',
            field=models.CharField(choices=[('textarea', 'Área de texto'), ('input', 'Campo de texto'), ('multiselect', 'Selección múltiple'), ('modules', 'Selector de módulos'), ('style_select', 'Selector de estilo visual'), ('color_picker', 'Selector de colores'), ('tone_select', 'Selector de tono')], default='input', help_text='Tipo de componente en la interfaz de onboarding', max_length=20, verbose_name='Tipo de input UI'),
        ),
    ]
