# Generated by Django 5.1.7 on 2026-06-01 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0017_add_style_color_tone_input_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador ej: testimonials', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Nombre visible ej: Testimonios', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descripcion corta', max_length=200)),
                ('page', models.ForeignKey(blank=True, help_text='Pagina a la que pertenece. NULL = seccion de Home', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='websites.websitepage')),
                ('is_default', models.BooleanField(default=False, help_text='La IA la incluye por defecto')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seccion de sitio web',
                'verbose_name_plural': 'Secciones de sitio web',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
