# Generated by Django 5.1.7 on 2026-06-03 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0018_websitesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True, verbose_name='Clave')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('category', models.CharField(choices=[('system', 'Sistema'), ('business', 'Negocio'), ('visual', 'Visual'), ('section', 'Secciones'), ('rules', 'Reglas')], default='system', max_length=20, verbose_name='Categoría')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('template', 'Template específico'), ('industry', 'Industria específica')], default='global', max_length=20, verbose_name='Alcance')),
                ('industry', models.CharField(blank=True, choices=[('restaurant', 'Restaurante / Café'), ('retail', 'Tienda / Retail'), ('beauty', 'Salón de Belleza / Spa'), ('health', 'Salud / Clínica'), ('fitness', 'Gimnasio / Fitness'), ('professional', 'Servicios Profesionales'), ('education', 'Educación / Academia'), ('automotive', 'Automotriz / Taller'), ('real_estate', 'Inmobiliaria'), ('events', 'Eventos / Catering'), ('pet', 'Mascotas / Veterinaria'), ('tech', 'Tecnología / Startup'), ('creative', 'Creativo / Agencia'), ('consulting', 'Consultoría'), ('generic', 'Negocio General')], max_length=50, verbose_name='Industria')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_blocks', to='websites.websitetemplate')),
            ],
            options={
                'verbose_name': 'Bloque de prompt',
                'verbose_name_plural': 'Bloques de prompt',
                'ordering': ['category', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SectionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True, verbose_name='Clave')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('css_class_hint', models.CharField(blank=True, max_length=100, verbose_name='Clase CSS sugerida')),
                ('preview_url', models.URLField(blank=True, verbose_name='URL de preview')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('industries', models.JSONField(blank=True, default=list, verbose_name='Industrias')),
                ('mood', models.CharField(choices=[('professional', 'Profesional'), ('playful', 'Lúdico'), ('elegant', 'Elegante'), ('bold', 'Audaz'), ('minimal', 'Minimalista')], default='professional', max_length=20, verbose_name='Mood')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='websites.websitesection', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Variante de sección',
                'verbose_name_plural': 'Variantes de sección',
                'ordering': ['section', 'sort_order', 'label'],
            },
        ),
    ]
