# Generated by Django 5.1.7 on 2026-06-03 18:21
"""Seed data: PromptBlocks (from hardcoded ai_prompts.py) + Hero SectionVariants."""

from django.db import migrations

PROMPT_BLOCKS = [
    {
        "key": "system-role",
        "label": "Rol del sistema",
        "content": (
            "Eres un experto en crear contenido para sitios web de negocios.\n"
            "Tu objetivo es generar contenido profesional, atractivo y personalizado."
        ),
        "category": "system",
        "scope": "global",
        "sort_order": 0,
    },
    {
        "key": "business-context",
        "label": "Contexto del negocio",
        "content": "## Información del Negocio\n{business_context}",
        "category": "business",
        "scope": "global",
        "sort_order": 0,
    },
    {
        "key": "visual-config",
        "label": "Configuración visual",
        "content": "## Configuración Visual\n{visual_context}",
        "category": "visual",
        "scope": "global",
        "sort_order": 0,
    },
    {
        "key": "template-instructions",
        "label": "Instrucciones del template",
        "content": "## Instrucciones del Template\n{template_prompt}",
        "category": "system",
        "scope": "template",
        "sort_order": 10,
    },
    {
        "key": "variant-instructions",
        "label": "Instrucciones de variantes",
        "content": "{variant_instructions}",
        "category": "section",
        "scope": "global",
        "sort_order": 10,
    },
    {
        "key": "rules-general",
        "label": "Reglas generales",
        "content": (
            "## Reglas Generales\n"
            "1. Escribe en español (España/Latinoamérica según el contexto)\n"
            "2. Usa un tono {brand_tone}\n"
            "3. Sé conciso pero impactante\n"
            "4. Incluye llamadas a la acción claras\n"
            "5. Personaliza el contenido según la industria y audiencia\n"
            "6. No inventes información que no se haya proporcionado\n"
            '7. Si falta información, usa placeholders descriptivos como "[Tu teléfono]"'
        ),
        "category": "rules",
        "scope": "global",
        "sort_order": 0,
    },
    {
        "key": "rules-json-format",
        "label": "Formato JSON de respuesta",
        "content": (
            "## Formato de Respuesta\n"
            "Responde SIEMPRE en formato JSON válido con la estructura solicitada.\n"
            "No incluyas explicaciones fuera del JSON."
        ),
        "category": "rules",
        "scope": "global",
        "sort_order": 10,
    },
]

HERO_VARIANTS = [
    {
        "key": "hero-split-image",
        "label": "Split con imagen",
        "description": "Texto a la izquierda, imagen a la derecha. Layout clásico y versátil.",
        "css_class_hint": "hero--split-image",
        "tags": ["imagen", "split"],
        "industries": [],
        "mood": "professional",
        "is_default": True,
        "sort_order": 0,
    },
    {
        "key": "hero-fullwidth-image",
        "label": "Imagen a ancho completo",
        "description": "Imagen de fondo con overlay y texto centrado. Alto impacto visual.",
        "css_class_hint": "hero--fullwidth-image",
        "tags": ["imagen", "fullwidth", "overlay"],
        "industries": [],
        "mood": "bold",
        "is_default": False,
        "sort_order": 1,
    },
    {
        "key": "hero-diagonal-split",
        "label": "Diagonal split",
        "description": "División diagonal entre imagen y contenido. Elegante y moderno.",
        "css_class_hint": "hero--diagonal-split",
        "tags": ["imagen", "diagonal"],
        "industries": [],
        "mood": "elegant",
        "is_default": False,
        "sort_order": 2,
    },
    {
        "key": "hero-centered",
        "label": "Centrado sin imagen",
        "description": "Texto centrado con CTA prominente. Limpio y directo.",
        "css_class_hint": "hero--centered",
        "tags": ["sin-imagen", "centrado"],
        "industries": [],
        "mood": "minimal",
        "is_default": False,
        "sort_order": 3,
    },
    {
        "key": "hero-bold-typography",
        "label": "Tipografía bold",
        "description": "Título grande y llamativo sin imagen. Ideal para marcas con personalidad fuerte.",
        "css_class_hint": "hero--bold-typography",
        "tags": ["sin-imagen", "tipografia"],
        "industries": [],
        "mood": "bold",
        "is_default": False,
        "sort_order": 4,
    },
    {
        "key": "hero-glassmorphism",
        "label": "Glassmorphism",
        "description": "Efecto cristal con fondo difuminado. Sofisticado y contemporáneo.",
        "css_class_hint": "hero--glassmorphism",
        "tags": ["sin-imagen", "glassmorphism"],
        "industries": [],
        "mood": "elegant",
        "is_default": False,
        "sort_order": 5,
    },
]


def seed_data(apps, schema_editor):
    PromptBlock = apps.get_model("websites", "PromptBlock")
    SectionVariant = apps.get_model("websites", "SectionVariant")
    WebsiteSection = apps.get_model("websites", "WebsiteSection")

    # Create PromptBlocks (skip if key already exists)
    for block_data in PROMPT_BLOCKS:
        PromptBlock.objects.get_or_create(
            key=block_data["key"],
            defaults=block_data,
        )

    # Create Hero SectionVariants (only if hero section exists)
    try:
        hero_section = WebsiteSection.objects.get(key="hero")
    except WebsiteSection.DoesNotExist:
        return

    for variant_data in HERO_VARIANTS:
        SectionVariant.objects.get_or_create(
            key=variant_data["key"],
            defaults={**variant_data, "section": hero_section},
        )


def reverse_seed(apps, schema_editor):
    PromptBlock = apps.get_model("websites", "PromptBlock")
    SectionVariant = apps.get_model("websites", "SectionVariant")

    block_keys = [b["key"] for b in PROMPT_BLOCKS]
    PromptBlock.objects.filter(key__in=block_keys).delete()

    variant_keys = [v["key"] for v in HERO_VARIANTS]
    SectionVariant.objects.filter(key__in=variant_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0019_promptblock_sectionvariant"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]
