# Generated by Django 5.1.7 on 2026-06-04 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_data_consent_ip'),
        ('websites', '0024_fix_retired_haiku_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_description', models.TextField(verbose_name='Descripción del negocio')),
                ('selected_modules', models.JSONField(blank=True, default=list, verbose_name='Módulos seleccionados')),
                ('description_normalized', models.CharField(blank=True, db_index=True, help_text='Slug del texto para deduplicar / lookup de caché', max_length=255, verbose_name='Descripción normalizada')),
                ('predicted_key', models.CharField(max_length=50, verbose_name='Industria predicha (key)')),
                ('predicted_label', models.CharField(max_length=120, verbose_name='Industria predicha (label)')),
                ('predicted_confidence', models.FloatField(default=0.0, verbose_name='Confianza')),
                ('is_new', models.BooleanField(default=False, help_text='True si la IA propuso una industria nueva', verbose_name='Industria nueva')),
                ('source', models.CharField(choices=[('haiku', 'Haiku (IA)'), ('cache', 'Caché (dataset propio)'), ('mock', 'Mock (sin IA)')], default='haiku', max_length=10, verbose_name='Origen de la predicción')),
                ('user_action', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('corrected', 'Corregida')], default='pending', max_length=10, verbose_name='Acción del usuario')),
                ('final_key', models.CharField(blank=True, max_length=50, verbose_name='Industria final (key)')),
                ('final_label', models.CharField(blank=True, max_length=120, verbose_name='Industria final (label)')),
                ('correction_text', models.TextField(blank=True, help_text='Lo que escribió el usuario al corregir', verbose_name='Texto de corrección')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Modelo usado')),
                ('tokens_input', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada')),
                ('tokens_output', models.PositiveIntegerField(default=0, verbose_name='Tokens de salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_classifications', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Clasificación de Industria',
                'verbose_name_plural': 'Clasificaciones de Industria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['description_normalized', 'user_action'], name='websites_in_descrip_49b62d_idx')],
            },
        ),
    ]
