# Generated by Django 5.1.7 on 2026-01-27 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_add_otp_token'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('code', models.CharField(help_text='Código único del cupón (ej: VERANO2024)', max_length=50, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción interna del cupón', verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto Fijo'), ('free_shipping', 'Envío Gratis')], default='percentage', max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo según el tipo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Descuento')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo requerido para aplicar el cupón', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Compra Mínima')),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Límite máximo del descuento (solo para porcentaje)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Máximo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_until', models.DateTimeField(verbose_name='Válido Hasta')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para uso ilimitado', null=True, verbose_name='Usos Máximos')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Cuántas veces puede usar el cupón un mismo usuario', verbose_name='Usos por Usuario')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('first_purchase_only', models.BooleanField(default=False, help_text='Cupón solo válido para usuarios sin compras previas', verbose_name='Solo Primera Compra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento Aplicado')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon', verbose_name='Cupón')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='Orden')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Uso de Cupón',
                'verbose_name_plural': 'Usos de Cupones',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_coupon_code_per_tenant'),
        ),
    ]
