# Generated by Django 5.1.15 on 2025-12-16 23:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del tenant (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre comercial del centro de estética', max_length=200, verbose_name='Nombre del negocio')),
                ('slug', models.SlugField(help_text='Se usa para subdominios: gc-belleza.tuapp.com', max_length=100, unique=True, verbose_name='Identificador único')),
                ('schema_name', models.CharField(db_index=True, help_text='Schema de PostgreSQL para este tenant (sin espacios ni caracteres especiales)', max_length=63, unique=True, verbose_name='Nombre del schema PostgreSQL')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección completa')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Provincia/Estado')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar si el cliente deja de pagar', verbose_name='¿Está activo?')),
                ('plan', models.CharField(choices=[('trial', 'Prueba (30 días)'), ('basic', 'Básico'), ('professional', 'Profesional'), ('enterprise', 'Empresarial')], default='trial', max_length=50, verbose_name='Plan contratado')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='Fin del periodo de prueba')),
                ('subscription_ends_at', models.DateField(blank=True, null=True, verbose_name='Fin de la suscripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo del negocio')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Color principal de la marca (ej: #3B82F6)', max_length=7, verbose_name='Color primario (hex)')),
                ('secondary_color', models.CharField(default='#8B5CF6', max_length=7, verbose_name='Color secundario (hex)')),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=50, verbose_name='Zona horaria')),
                ('currency', models.CharField(default='EUR', help_text='Código ISO 4217 (EUR, USD, COP, etc.)', max_length=3, verbose_name='Moneda')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('ca', 'Català')], default='es', max_length=10, verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cliente (Tenant)',
                'verbose_name_plural': 'Clientes (Tenants)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='core_tenant_slug_bb8545_idx'), models.Index(fields=['schema_name'], name='core_tenant_schema__08492e_idx'), models.Index(fields=['is_active'], name='core_tenant_is_acti_99418a_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Foto de perfil')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('staff', 'Empleado'), ('customer', 'Cliente')], default='customer', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(help_text='Centro de estética al que pertenece este usuario', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'email'], name='core_user_tenant__ee6577_idx'), models.Index(fields=['tenant', 'role'], name='core_user_tenant__469ef1_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'email'), name='unique_email_per_tenant')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
