# Generated by Django 5.1.15 on 2025-12-18 22:56

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.TenantAwareUserManager()),
            ],
        ),
    ]
