# Generated by Claude - Multi-tenant authentication with uid field

from django.db import migrations, models


def generate_uid_for_existing_users(apps, schema_editor):
    """
    Genera uid para usuarios existentes.
    Formato: tenant_slug:email o platform:email
    """
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        if user.tenant:
            user.uid = f"{user.tenant.slug}:{user.email}"
        else:
            user.uid = f"platform:{user.email}"
        user.save(update_fields=['uid'])


def reverse_uid(apps, schema_editor):
    """Reverse migration - set uid to empty string"""
    User = apps.get_model('core', 'User')
    User.objects.update(uid='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_email_auth_username_per_tenant'),
    ]

    operations = [
        # 1. Agregar campo uid como nullable primero
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Identificador único global (generado automáticamente)',
                max_length=150,
                verbose_name='UID interno',
            ),
            preserve_default=False,
        ),

        # 2. Generar uid para usuarios existentes
        migrations.RunPython(generate_uid_for_existing_users, reverse_uid),

        # 3. Hacer uid unique después de llenarlo
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Identificador único global (generado automáticamente)',
                max_length=150,
                unique=True,
                verbose_name='UID interno',
            ),
        ),

        # 4. Quitar unique=True del email (ahora es único por tenant solamente)
        # El constraint unique_email_per_tenant ya existe desde 0001
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                help_text='Email del usuario (único por tenant)',
                max_length=254,
                verbose_name='Email',
            ),
        ),
    ]