# Generated by Django 6.0 on 2025-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_uid_multi_tenant_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='True si la cuenta fue creada automáticamente al reservar como invitado', verbose_name='¿Es cuenta de invitado?'),
        ),
    ]
