# Generated by Django 6.0 on 2025-12-27 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_is_guest_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_set_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Contraseña',
                'verbose_name_plural': 'Tokens de Contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
