# Generated by Django 6.0 on 2026-01-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_password_set_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(help_text='Para identificar el banner en el admin (no se muestra al público)', max_length=100, verbose_name='Nombre interno')),
                ('message', models.TextField(help_text='Texto que se mostrará en el banner. Puede incluir HTML básico.', verbose_name='Mensaje')),
                ('link_url', models.URLField(blank=True, help_text='Si se proporciona, el banner será clickeable', null=True, verbose_name='URL del enlace')),
                ('link_text', models.CharField(blank=True, help_text="Texto para el botón/enlace (ej: 'Ver más', 'Comprar ahora')", max_length=50, verbose_name='Texto del enlace')),
                ('banner_type', models.CharField(choices=[('info', 'Informativo'), ('promo', 'Promoción'), ('warning', 'Aviso'), ('announcement', 'Anuncio')], default='promo', max_length=20, verbose_name='Tipo de banner')),
                ('position', models.CharField(choices=[('top', 'Arriba (encima del header)'), ('bottom', 'Abajo (encima del footer)')], default='top', max_length=10, verbose_name='Posición')),
                ('background_color', models.CharField(default='#3B82F6', help_text='Color de fondo del banner (ej: #3B82F6)', max_length=7, verbose_name='Color de fondo (hex)')),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Color del texto (ej: #FFFFFF para blanco)', max_length=7, verbose_name='Color del texto (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Si está activo, el usuario puede cerrar el banner', verbose_name='¿Se puede cerrar?')),
                ('start_date', models.DateTimeField(blank=True, help_text='Si se define, el banner solo se mostrará a partir de esta fecha', null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, help_text='Si se define, el banner dejará de mostrarse después de esta fecha', null=True, verbose_name='Fecha de fin')),
                ('priority', models.PositiveIntegerField(default=0, help_text='A mayor número, más prioritario. Se muestra primero el de mayor prioridad.', verbose_name='Prioridad')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
