# Generated by Django 6.0 on 2026-01-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='rotation_interval',
            field=models.PositiveIntegerField(default=5000, help_text='Tiempo en milisegundos entre cada rotación de banners. Por defecto: 5000ms (5 segundos)', verbose_name='Intervalo de rotación (ms)'),
        ),
    ]
