# Generated by Django 5.1.7 on 2026-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_banner_rotation_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, editable=False, help_text='Identificador único: tenant:email (generado automáticamente)', max_length=150, unique=True, verbose_name='Username (Email)'),
        ),
    ]
