# Generated by Django 5.1.7 on 2026-01-10 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de 6 dígitos', max_length=6, verbose_name='Código OTP')),
                ('purpose', models.CharField(choices=[('password_reset', 'Restablecer contraseña'), ('account_reactivation', 'Reactivar cuenta')], max_length=30, verbose_name='Propósito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos incorrectos', verbose_name='Intentos fallidos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token OTP',
                'verbose_name_plural': 'Tokens OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='core_otptok_user_id_b8ec17_idx')],
            },
        ),
    ]
