# Generated by Django 5.1.7 on 2026-02-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_staff_is_staff_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Valoración promedio del negocio (0-5, se muestra en la web)', max_digits=2, verbose_name='Valoración promedio'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='clients_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de clientes atendidos (se muestra en la web)', verbose_name='Clientes atendidos'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='treatments_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de tratamientos ofrecidos (se muestra en la web)', verbose_name='Tratamientos disponibles'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Años de experiencia del negocio (se muestra en la web)', verbose_name='Años de experiencia'),
        ),
    ]
