# Generated by Django 5.1.7 on 2026-02-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_tenant_hero_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Mi Negocio',
                'verbose_name_plural': 'Mi Negocio',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tenant',),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('Colombia', 'Colombia'), ('México', 'México'), ('España', 'España'), ('Perú', 'Perú'), ('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Venezuela', 'Venezuela'), ('Ecuador', 'Ecuador'), ('Panamá', 'Panamá'), ('Costa Rica', 'Costa Rica'), ('Guatemala', 'Guatemala'), ('Estados Unidos', 'Estados Unidos'), ('Brasil', 'Brasil'), ('Francia', 'Francia'), ('Reino Unido', 'Reino Unido'), ('Alemania', 'Alemania'), ('Italia', 'Italia'), ('Portugal', 'Portugal')], default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('COP', 'COP - Peso Colombiano'), ('USD', 'USD - Dólar Estadounidense'), ('EUR', 'EUR - Euro'), ('MXN', 'MXN - Peso Mexicano'), ('PEN', 'PEN - Sol Peruano'), ('CLP', 'CLP - Peso Chileno'), ('ARS', 'ARS - Peso Argentino'), ('VES', 'VES - Bolívar Venezolano'), ('BRL', 'BRL - Real Brasileño'), ('GBP', 'GBP - Libra Esterlina')], default='COP', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(choices=[('America/Bogota', 'Colombia (Bogotá) UTC-5'), ('America/Mexico_City', 'México (Ciudad de México) UTC-6'), ('America/Lima', 'Perú (Lima) UTC-5'), ('America/Santiago', 'Chile (Santiago) UTC-3/-4'), ('America/Buenos_Aires', 'Argentina (Buenos Aires) UTC-3'), ('America/Caracas', 'Venezuela (Caracas) UTC-4'), ('America/Guayaquil', 'Ecuador (Guayaquil) UTC-5'), ('America/Panama', 'Panamá UTC-5'), ('America/Costa_Rica', 'Costa Rica UTC-6'), ('America/Guatemala', 'Guatemala UTC-6'), ('America/New_York', 'Estados Unidos (Nueva York) UTC-5/-4'), ('America/Los_Angeles', 'Estados Unidos (Los Ángeles) UTC-8/-7'), ('America/Sao_Paulo', 'Brasil (São Paulo) UTC-3'), ('Europe/Madrid', 'España (Madrid) UTC+1/+2'), ('Europe/Paris', 'Francia (París) UTC+1/+2'), ('Europe/London', 'Reino Unido (Londres) UTC+0/+1'), ('Europe/Berlin', 'Alemania (Berlín) UTC+1/+2'), ('Europe/Rome', 'Italia (Roma) UTC+1/+2'), ('Europe/Lisbon', 'Portugal (Lisboa) UTC+0/+1')], default='America/Bogota', max_length=50, verbose_name='Zona horaria'),
        ),
    ]
