# Generated by Django 5.1.7 on 2026-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_tenant_regional_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='Se usa para subdominios: gc-belleza.tuapp.com (máx 60 caracteres)', max_length=60, unique=True, verbose_name='Identificador único'),
        ),
    ]
