# Generated by Django 5.1.7 on 2026-02-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adjust_tenant_slug_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_bookings',
            field=models.BooleanField(default=True, help_text='Habilita: Servicios, Staff, Citas, Horarios, Días libres', verbose_name='GRAVITI Bookings'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_marketing',
            field=models.BooleanField(default=False, help_text='Habilita: Cupones, Promociones, Reseñas (requiere Shop o Bookings)', verbose_name='Marketing'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_shop',
            field=models.BooleanField(default=True, help_text='Habilita: Productos, Categorías, Inventario, Órdenes, Carritos', verbose_name='GRAVITI Shop'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, help_text='Generado automáticamente: slug_db (ej: pixel_sabana_db)', max_length=63, unique=True, verbose_name='Nombre del schema PostgreSQL'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento/Provincia/Estado'),
        ),
    ]
