# Generated by Django 5.1.7 on 2026-02-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_unify_subscription_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_services',
            field=models.BooleanField(default=False, help_text='Habilita: Servicios vendibles (planes, seguros, membresías) sin agendar', verbose_name='GRAVITI Services'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_bookings',
            field=models.BooleanField(default=True, help_text='Habilita: Servicios agendables, Staff, Citas, Horarios, Días libres', verbose_name='GRAVITI Bookings'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_marketing',
            field=models.BooleanField(default=False, help_text='Habilita: Cupones, Promociones, Reseñas (requiere Shop, Bookings o Services)', verbose_name='Marketing'),
        ),
    ]
