# Generated by Django 5.1.7 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_has_services_to_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='has_marketing',
            field=models.BooleanField(default=False, help_text='Habilita: Cupones, Promociones, Reseñas (requiere Shop, Bookings o Services)', verbose_name='GRAVITI Marketing'),
        ),
    ]
