# Generated by Django 5.1.7 on 2026-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_update_marketing_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebsite',
            fields=[
            ],
            options={
                'verbose_name': 'Mi Sitio Web',
                'verbose_name_plural': 'Mi Sitio Web',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tenant',),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se mostrará en el panel de administración', null=True, upload_to='tenants/logos/', verbose_name='Logo del negocio'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='El nombre comercial que verán tus clientes', max_length=200, verbose_name='Nombre del negocio'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, help_text='Generado automáticamente', max_length=63, unique=True, verbose_name='ID interno DB'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='Identificador único'),
        ),
    ]
