# Generated by Django 5.1.7 on 2026-02-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenantwebsite_alter_tenant_logo_alter_tenant_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='El nombre comercial del cliente', max_length=200, verbose_name='Nombre del cliente'),
        ),
    ]
