# Generated by Django 5.1.7 on 2026-02-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_tenant_options_alter_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.CharField(blank=True, choices=[('gym', 'Gimnasio / Fitness'), ('beauty', 'Salón de Belleza / Spa'), ('restaurant', 'Restaurante / Cafetería'), ('clinic', 'Clínica / Consultorio'), ('store', 'Tienda / Retail'), ('services', 'Servicios Profesionales'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de negocio'),
        ),
    ]
