# Generated by Django 5.1.7 on 2026-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tenant_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='has_bookings',
            field=models.BooleanField(default=True, help_text='Habilita: Servicios agendables, Staff, Citas, Horarios, Días libres', verbose_name='Bookings'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_marketing',
            field=models.BooleanField(default=False, help_text='Habilita: Cupones, Promociones, Reseñas (requiere Shop, Bookings o Services)', verbose_name='Marketing'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_services',
            field=models.BooleanField(default=False, help_text='Habilita: Servicios vendibles (planes, seguros, membresías) sin agendar', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_shop',
            field=models.BooleanField(default=True, help_text='Habilita: Productos, Categorías, Inventario, Órdenes, Carritos', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='industry',
            field=models.CharField(blank=True, choices=[('beauty', 'Salón de Belleza / Barbería'), ('spa', 'Spa / Centro de Bienestar'), ('nails', 'Uñas / Nail Bar'), ('gym', 'Gimnasio / Fitness'), ('yoga', 'Yoga / Pilates / Danza'), ('clinic', 'Clínica / Consultorio Médico'), ('dental', 'Odontología'), ('psychology', 'Psicología / Terapias'), ('nutrition', 'Nutrición / Dietética'), ('veterinary', 'Veterinaria / Pet Shop'), ('restaurant', 'Restaurante / Cafetería'), ('bakery', 'Panadería / Pastelería'), ('store', 'Tienda / Retail'), ('fashion', 'Moda / Boutique'), ('education', 'Educación / Academia'), ('coworking', 'Coworking / Oficina'), ('photography', 'Fotografía / Videografía'), ('architecture', 'Arquitectura / Diseño'), ('legal', 'Abogados / Consultoría Legal'), ('accounting', 'Contabilidad / Finanzas'), ('marketing', 'Marketing / Publicidad'), ('tech', 'Tecnología / Software'), ('real_estate', 'Inmobiliaria'), ('automotive', 'Automotriz / Taller Mecánico'), ('events', 'Eventos / Wedding Planner'), ('travel', 'Turismo / Agencia de Viajes'), ('services', 'Servicios Profesionales'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Tipo de negocio'),
        ),
    ]
