# Generated by Django 5.1.7 on 2026-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tenant_has_bookings_alter_tenant_has_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modules_configured',
            field=models.BooleanField(default=False, help_text='True cuando el dueño del negocio ya eligió sus módulos.', verbose_name='Módulos configurados'),
        ),
    ]
