# Generated by Django 5.1.7 on 2026-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_modules_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_website',
            field=models.BooleanField(default=False, help_text='Habilita: Sitio web estático generado con IA', verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_bookings',
            field=models.BooleanField(default=False, help_text='Habilita: Servicios agendables, Staff, Citas, Horarios, Días libres', verbose_name='Bookings'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='has_shop',
            field=models.BooleanField(default=False, help_text='Habilita: Productos, Categorías, Inventario, Órdenes, Carritos', verbose_name='Shop'),
        ),
    ]
