# Generated by Django 5.1.7 on 2026-03-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_has_website_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('facebook', 'Facebook')], max_length=20, verbose_name='Proveedor')),
                ('provider_uid', models.CharField(help_text='ID único del usuario en el proveedor (sub/id)', max_length=255, verbose_name='ID del proveedor')),
                ('email', models.EmailField(help_text='Email asociado en la cuenta social', max_length=254, verbose_name='Email del proveedor')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Nombre, avatar, etc. del proveedor', verbose_name='Datos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta Social',
                'verbose_name_plural': 'Cuentas Sociales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'provider', 'email'], name='core_social_tenant__a9e4fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider', 'provider_uid'), name='unique_social_account_per_tenant')],
            },
        ),
    ]
