# Generated by Django 5.1.7 on 2026-04-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_has_website_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='message',
            field=models.TextField(help_text='Texto plano que se mostrará en el banner. HTML será eliminado automáticamente.', verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='code',
            field=models.CharField(help_text='Código de 8 dígitos', max_length=8, verbose_name='Código OTP'),
        ),
    ]
