# Generated by Django 5.1.7 on 2026-04-19 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_has_website_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del invitado')),
                ('role', models.CharField(choices=[('staff', 'Empleado'), ('admin', 'Administrador')], default='staff', max_length=20, verbose_name='Rol asignado')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de invitación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada')),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creado')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('tenant', models.ForeignKey(help_text='Tenant al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Invitación de equipo',
                'verbose_name_plural': 'Invitaciones de equipo',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant', 'email'), name='unique_pending_invitation_per_tenant')],
            },
        ),
    ]
