# Generated by Django 5.1.7 on 2026-04-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_superadmin_email_unique'),
        ('core', '0031_totp_device'),
    ]

    operations = [
    ]
