# Generated by Django 5.1.7 on 2026-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_team_invitation'),
        ('core', '0032_merge_0031_superadmin_email_unique_0031_totp_device'),
    ]

    operations = [
    ]
