# Generated by Django 5.1.7 on 2026-04-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_merge_0031_superadmin_email_unique_0031_totp_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("deactivate_tenant", "Deactivate tenant"),
                            ("activate_tenant", "Activate tenant"),
                            ("deactivate_user", "Deactivate user"),
                            ("activate_user", "Activate user"),
                            ("change_user_role", "Change user role"),
                            ("delete_passkey", "Delete passkey"),
                            ("disable_2fa", "Disable 2FA"),
                            ("unlink_social", "Unlink social account"),
                            ("reset_password", "Reset password"),
                        ],
                        max_length=30,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Nombre del modelo objetivo, ej: 'Tenant', 'User', 'WebAuthnCredential'.",
                        max_length=50,
                        verbose_name="Tipo de objetivo",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="PK del objetivo como string. Soporta UUID (Tenant) e int (User).",
                        max_length=255,
                        verbose_name="ID del objetivo",
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        help_text=(
                            "Descripción legible del objetivo, ej: 'tenant: mi-tienda' "
                            "o 'user: juan@example.com'."
                        ),
                        max_length=300,
                        verbose_name="Representación del objetivo",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contexto adicional opcional, ej: {'old_role': 'customer', 'new_role': 'admin'}.",
                        verbose_name="Detalles",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP del cliente que originó la acción (X-Forwarded-For o REMOTE_ADDR).",
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Creado",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Superadmin que ejecutó la acción. NULL si el actor fue eliminado "
                            "o fue una acción de sistema."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Audit Log",
                "verbose_name_plural": "Admin Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(fields=["actor", "-created_at"], name="core_admina_actor_i_de0819_idx"),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(fields=["action", "-created_at"], name="core_admina_action_0bd741_idx"),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(fields=["target_type", "target_id"], name="core_admina_target__1d4d61_idx"),
        ),
    ]
