# Generated by Django 5.1.7 on 2026-04-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_0031_superadmin_email_unique_0031_totp_device'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webauthncredential',
            new_name='core_webaut_user_id_7d5c9a_idx',
            old_name='core_webaut_user_id_idx',
        ),
        migrations.AlterField(
            model_name='banner',
            name='message',
            field=models.TextField(help_text='Texto plano que se mostrará en el banner. HTML será eliminado automáticamente.', verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='code',
            field=models.CharField(help_text='Código de 8 dígitos', max_length=8, verbose_name='Código OTP'),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
