# Generated by Django 5.1.7 on 2026-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_admin_audit_log'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='core_socialaccount_user_provider_uq'),
        ),
    ]
