# Generated by Django 5.1.7 on 2026-04-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_unique_user_provider_to_socialaccount'),
        ('core', '0034_otp_8digit_code_banner_text'),
    ]

    operations = [
    ]
