# Generated by Django 5.1.7 on 2026-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('deactivate_tenant', 'Deactivate tenant'), ('activate_tenant', 'Activate tenant'), ('edit_tenant_data', 'Edit tenant data'), ('deactivate_user', 'Deactivate user'), ('activate_user', 'Activate user'), ('change_user_role', 'Change user role'), ('delete_passkey', 'Delete passkey'), ('disable_2fa', 'Disable 2FA'), ('unlink_social', 'Unlink social account'), ('reset_password', 'Reset password')], max_length=30, verbose_name='Acción'),
        ),
    ]
