# Generated by Django 5.1.7 on 2026-04-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_team_invitation'),
        ('core', '0036_add_edit_tenant_data_audit_action'),
    ]

    operations = [
    ]
