# Generated by Django 5.1.7 on 2026-04-28 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_initial_superadmin_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    superadmins = User.objects.filter(is_superuser=True, tenant__isnull=True)

    for sa in superadmins:
        sa.superadmin_status = "active" if sa.is_active else "deactivated"
        sa.internal_role = "admin"
        sa.save(update_fields=["superadmin_status", "internal_role"])

    # Mark first superadmin as owner
    first = superadmins.order_by("id").first()
    if first:
        first.is_owner = True
        first.internal_role = "owner"
        first.save(update_fields=["is_owner", "internal_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0037_merge_20260422_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_superadmins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('support', 'Soporte'), ('viewer', 'Viewer')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='superadmin_status',
            field=models.CharField(choices=[('active', 'Activo'), ('blocked', 'Bloqueado'), ('deactivated', 'Desactivado')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('deactivate_tenant', 'Deactivate tenant'), ('activate_tenant', 'Activate tenant'), ('edit_tenant_data', 'Edit tenant data'), ('deactivate_user', 'Deactivate user'), ('activate_user', 'Activate user'), ('change_user_role', 'Change user role'), ('delete_passkey', 'Delete passkey'), ('disable_2fa', 'Disable 2FA'), ('unlink_social', 'Unlink social account'), ('reset_password', 'Reset password'), ('block_superadmin', 'Bloquear superadmin'), ('unblock_superadmin', 'Desbloquear superadmin'), ('delete_superadmin', 'Eliminar superadmin'), ('change_superadmin_role', 'Cambiar rol de superadmin'), ('create_superadmin', 'Crear superadmin')], max_length=40, verbose_name='Acción'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['superadmin_status'], name='core_user_sa_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True), ('is_superuser', True), ('tenant__isnull', True)), fields=('is_owner',), name='core_user_single_owner_uq'),
        ),
        migrations.RunPython(
            set_initial_superadmin_data,
            migrations.RunPython.noop,
        ),
    ]
