# Generated by Django 5.1.7 on 2026-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_tenant_phase_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_management',
            field=models.BooleanField(default=False, help_text='Habilita: Ventas, Compras, Gastos, Proveedores, Movimientos de inventario', verbose_name='Gestion Comercial'),
        ),
    ]
