# Generated by Django 5.1.7 on 2026-04-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_superadmin_management'),
        ('core', '0038_tenant_phase_log'),
    ]

    operations = [
    ]
