# Generated by Django 5.1.7 on 2026-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_management',
            field=models.BooleanField(default=False, help_text='Habilita: Solo módulos de gestión (sin sitio web público)', verbose_name='Gestión Interna'),
        ),
    ]
