# Generated by Django 5.1.7 on 2026-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_has_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador unico ej: has_services', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Nombre visible ej: Servicios', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descripcion corta del modulo', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono Lucide ej: briefcase', max_length=50)),
                ('accent_color', models.CharField(default='#0D9488', help_text='Color hex del modulo', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Si esta disponible para seleccion')),
                ('sort_order', models.IntegerField(default=0, help_text='Orden en el grid de seleccion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Modulos requeridos al activar este', related_name='dependents', to='core.platformmodule')),
            ],
            options={
                'verbose_name': 'Modulo de plataforma',
                'verbose_name_plural': 'Modulos de plataforma',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
