# Generated by Django 5.1.7 on 2026-05-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_enable_row_level_security'),
        ('core', '0041_platformmodule'),
    ]

    operations = [
    ]
