# Generated by Django 5.1.7 on 2026-05-23 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_create_nerbis_app_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(help_text='Identificador unico, ej: hero, faq, cta_final', max_length=50, unique=True, verbose_name='Clave de seccion')),
                ('content', models.JSONField(default=dict, help_text='Datos editables de la seccion en formato JSON', verbose_name='Contenido')),
                ('is_visible', models.BooleanField(default=True, help_text='Si la seccion se muestra en el sitio publico', verbose_name='Visible')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Posicion en la pagina (menor = mas arriba)', verbose_name='Orden')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Superadmin que hizo la ultima edicion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Seccion de Marketing',
                'verbose_name_plural': 'Secciones de Marketing',
                'ordering': ['sort_order'],
            },
        ),
    ]
