# Generated by Django 5.1.7 on 2026-05-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_marketingsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryGalleryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la industria, ej: Restaurantes', max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, help_text='Foto representativa de la industria (JPG, PNG, WebP, max 5MB)', null=True, upload_to='industries/', verbose_name='Imagen')),
                ('gradient', models.CharField(blank=True, default='', help_text='CSS gradient como fallback cuando no hay imagen', max_length=255, verbose_name='Gradiente CSS')),
                ('row', models.PositiveSmallIntegerField(choices=[(1, 'Fila 1'), (2, 'Fila 2')], default=1, help_text='Fila del marquee donde aparece la card', verbose_name='Fila')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Posicion dentro de la fila (menor = mas a la izquierda)', verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, help_text='Si la card se muestra en el sitio publico', verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Card de Galeria de Industrias',
                'verbose_name_plural': 'Cards de Galeria de Industrias',
                'ordering': ['row', 'sort_order'],
            },
        ),
    ]
