# Generated by Django 5.1.7 on 2026-05-28 03:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_marketingsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Dirección de notificación judicial'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIT / Identificación fiscal'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento de datos'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha consentimiento datos'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento de marketing'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha consentimiento marketing'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.19'), help_text='Ej: 0.19 para 19% (Colombia), 0.21 para 21% (España), 0.16 para 16% (México)', max_digits=5, verbose_name='Tasa de impuesto'),
        ),
    ]
