# Generated by Django 5.1.7 on 2026-05-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_industrygallerycard'),
        ('core', '0045_tenant_legal_address_tenant_legal_name_tenant_tax_id_and_more'),
    ]

    operations = [
    ]
