# Generated by Django 5.1.7 on 2026-06-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_tenant_legal_address_tenant_legal_name_tenant_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='True = en papelera. No se destruyen datos, solo se oculta del listado.', verbose_name='Eliminado (soft delete)'),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('deactivate_tenant', 'Deactivate tenant'), ('activate_tenant', 'Activate tenant'), ('edit_tenant_data', 'Edit tenant data'), ('delete_tenant', 'Soft delete tenant'), ('restore_tenant', 'Restore tenant'), ('deactivate_user', 'Deactivate user'), ('activate_user', 'Activate user'), ('change_user_role', 'Change user role'), ('delete_passkey', 'Delete passkey'), ('disable_2fa', 'Disable 2FA'), ('unlink_social', 'Unlink social account'), ('reset_password', 'Reset password'), ('block_superadmin', 'Bloquear superadmin'), ('unblock_superadmin', 'Desbloquear superadmin'), ('delete_superadmin', 'Eliminar superadmin'), ('change_superadmin_role', 'Cambiar rol de superadmin'), ('create_superadmin', 'Crear superadmin')], max_length=40, verbose_name='Acción'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_deleted'], name='core_tenant_is_dele_679e46_idx'),
        ),
    ]
