# Generated by Django 5.1.7 on 2026-05-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_tenant_legal_address_tenant_legal_name_tenant_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP consentimiento datos'),
        ),
    ]
