# Generated by Django 5.1.7 on 2026-06-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_industrygallerycard'),
        ('core', '0046_tenant_soft_delete'),
    ]

    operations = [
    ]
