# Generated by Django 5.1.7 on 2026-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_tenant_soft_delete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_deleted'], name='core_tenant_is_dele_679e46_idx'),
        ),
    ]
