# Generated by Django 5.1.7 on 2026-06-04 20:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_data_consent_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se mostrará en el panel de administración', null=True, upload_to=core.models.tenant_logo_upload_to, verbose_name='Logo del negocio'),
        ),
    ]
