# Generated by Django 5.1.7 on 2026-06-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_alter_tenant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ai_usage_reset_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca de tiempo del último reinicio manual del contador de uso de IA hecho por un superadmin. El conteo de generaciones usa el máximo entre el inicio del mes y esta fecha. NULL = sin reinicio manual (comportamiento mensual por defecto).",
                null=True,
                verbose_name="Reinicio de uso de IA",
            ),
        ),
    ]
